SELECT L.CODCOLIGADA [COLIGADA], L.CODFILIAL [FILIAL], L.IDLAF [IDLAF/IDLAN], L.IDLAFAGRUP, L.DOCINI [NUMERO NF], L.SERIEDOC [SERIE], L.CODTDO [TIPO DOC], 
       L.DATAEMISSAO EMISSAO, L.DATAES [ENTRADA/VECTO], NULL [DATA BAIXA],
       L.CODCFO [COD FORNEC], F.NOME, F.CGCCFO [CNPJ], 'IRRF PJ' TRIBUTO,
	   T.BASETRB [BASE], T.ALIQTRB [ALIQ], T.VALORTRB [VALOR], T.CODRETENCAO [COD RECEITA], N.CODNATRENDIMENTO [NATUREZA], N.DESCRICAORENDIMENTO [DESCRICAO],
	   CASE WHEN T.TIPORECOLHIMENTO=2 THEN 'RETIDO' ELSE '' END [TIPO RECOLH],
	   E.IDEVENTO

FROM   DTRBLAF T (NOLOCK)

LEFT OUTER JOIN DLAF L (NOLOCK) ON T.CODCOLIGADA = L.CODCOLIGADA AND T.IDLAF = L.IDLAF
LEFT OUTER JOIN FCFO F (NOLOCK) ON L.CODCOLCFO = F.CODCOLIGADA AND L.CODCFO = F.CODCFO
LEFT OUTER JOIN DNATUREZARENDIMENTO N (NOLOCK) ON T.IDNATRENDIMENTO = N.IDNATRENDIMENTO
LEFT OUTER JOIN DEVENTOREINFLANC R (NOLOCK) ON R.CODCOLIGADA = L.CODCOLIGADA AND R.IDLAFAGRUP = L.IDLAFAGRUP
LEFT OUTER JOIN DEVENTOREINF E (NOLOCK) ON R.CODCOLIGADA = E.CODCOLIGADA AND R.IDEVENTO = E.IDEVENTO AND E.TIPO=20

WHERE  L.DATAES>=:DATA_INICIAL_D
AND    L.DATAES<=:DATA_FINAL_D
AND    L.CODFILIAL>=:FILIAL_INICIAL_N
AND    L.CODFILIAL<=:FILIAL_FINAL_N
AND    L.CODCOLIGADA=:COLIGADA_N
AND    T.CODTRB LIKE 'IRRFPJ'


UNION ALL


SELECT L.CODCOLIGADA [COLIGADA], L.CODFILIAL [FILIAL], L.IDLAN [IDLAF/IDLAN], '' IDLAFAGRUP, L.NUMERODOCUMENTO [NUMERO NF], L.SERIEDOCUMENTO [SERIE], L.CODTDO [TIPO DOC], 
       L.DATAEMISSAO EMISSAO, L.DATAVENCIMENTO [ENTRADA/VECTO], L.DATABAIXA [DATA BAIXA],
       L.CODCFO [COD FORNEC], F.NOME, F.CGCCFO [CNPJ], 'TRB-RF' TRIBUTO,
	   T.BASEDECALCULO [BASE], T.ALIQUOTA [ALIQ], T.VALOR [VALOR], T.CODRETENCAO [COD RECEITA], N.CODNATRENDIMENTO [NATUREZA], N.DESCRICAORENDIMENTO [DESCRICAO],
	   'RETIDO' [TIPO RECOLH],
	   E.IDEVENTO

FROM   FTRBLAN T (NOLOCK)

INNER JOIN FLAN L (NOLOCK) ON T.CODCOLIGADA = L.CODCOLIGADA AND T.IDLAN = L.IDLAN
LEFT OUTER JOIN FCFO F (NOLOCK) ON L.CODCOLCFO = F.CODCOLIGADA AND L.CODCFO = F.CODCFO
LEFT OUTER JOIN DNATUREZARENDIMENTO N (NOLOCK) ON T.IDNATRENDIMENTO = N.IDNATRENDIMENTO
LEFT OUTER JOIN DEVENTOREINFLANCFIN R (NOLOCK) ON R.CODCOLIGADA = L.CODCOLIGADA AND R.IDLAN = L.IDLAN
LEFT OUTER JOIN DEVENTOREINF E (NOLOCK) ON R.CODCOLIGADA = E.CODCOLIGADA AND R.IDEVENTO = E.IDEVENTO AND E.TIPO=20

WHERE  L.DATABAIXA>=:DATA_INICIAL_D
AND    L.DATABAIXA<=:DATA_FINAL_D
AND    L.CODFILIAL>=:FILIAL_INICIAL_N
AND    L.CODFILIAL<=:FILIAL_FINAL_N
AND    L.CODCOLIGADA=:COLIGADA_N
AND    T.CODTRB LIKE 'TRB-RF'
AND    L.STATUSLAN<>2