SET DATEFORMAT DMY;
SET LANGUAGE 'BRAZILIAN';

SELECT
	 CHAPA			=	PFUNC.CHAPA
	,NOME			=	PFUNC.NOME
	,DT_INICIO		=	CONVERT(VARCHAR, VCHAPAATESTADO.DTINICIO, 103)
	,VCHAPAATESTADO.SEQATESTADO
	,VATESTADO.IDATESTADO
	,VATESTADO.IDATESTADO
	,VATESTADO.CID
	

	,VATESTADO.OBSERVACOES
	,VATESTADO.CHAPARESPABONO
	,VCHAPAATESTADO.MOTIVOAFAST
	,PMUDSITUACAO.DESCRICAO
FROM
					GCOLIGADA			(NOLOCK)
	INNER	JOIN	GFILIAL				(NOLOCK)	ON	GCOLIGADA.CODCOLIGADA			= GFILIAL.CODCOLIGADA
	INNER	JOIN	GIMAGEM				 (NOLOCK)	ON	GIMAGEM.ID						= GFILIAL.IDIMAGEM
	INNER	JOIN	PFUNC				(NOLOCK)	ON	GFILIAL.CODCOLIGADA				= PFUNC.CODCOLIGADA				
													AND GFILIAL.CODFILIAL				= PFUNC.CODFILIAL
	INNER	JOIN	PPESSOA				(NOLOCK)	ON	PFUNC.CODPESSOA					= PPESSOA.CODIGO
	LEFT	JOIN	PFUNCAO				(NOLOCK)	ON	PFUNC.CODCOLIGADA				= PFUNCAO.CODCOLIGADA			
													AND PFUNC.CODFUNCAO					= PFUNCAO.CODIGO
	LEFT	JOIN	AABONOFUNCIONARIO	(NOLOCK)	ON	PFUNC.CODCOLIGADA				= AABONOFUNCIONARIO.CODCOLIGADA
													AND	PFUNC.CHAPA						= AABONOFUNCIONARIO.CHAPA
	INNER	JOIN	VCHAPAATESTADO		(NOLOCK)	ON	PFUNC.CODCOLIGADA				= VCHAPAATESTADO.CODCOLIGADA	
													AND PFUNC.CHAPA						= VCHAPAATESTADO.CHAPA
	INNER	JOIN	VATESTADO			(NOLOCK)	ON	VCHAPAATESTADO.CODPESSOA		= VATESTADO.CODPESSOA
													AND	VCHAPAATESTADO.SEQATESTADO		= VATESTADO.SEQATESTADO
													AND	VCHAPAATESTADO.DTINICIO			= VATESTADO.DTINICIO
													AND	VCHAPAATESTADO.CODTPATESTADO	= VATESTADO.CODTPATESTADO
	INNER	JOIN	VTIPOATESTADO		(NOLOCK)	ON	VATESTADO.CODTPATESTADO			= VTIPOATESTADO.CODTPATESTADO
	INNER	JOIN	VABONOTPATESTADO	(NOLOCK)	ON	VTIPOATESTADO.CODTPATESTADO		= VABONOTPATESTADO.CODTPATESTADO
	INNER	JOIN	AABONO				(NOLOCK)	ON	VABONOTPATESTADO.CODCOLIGADA	= AABONO.CODCOLIGADA
													AND	VABONOTPATESTADO.CODABONO		= AABONO.CODIGO
													AND	GCOLIGADA.CODCOLIGADA			= AABONO.CODCOLIGADA
	LEFT	JOIN	PMUDSITUACAO		(NOLOCK)	ON	VCHAPAATESTADO.CODCOLIGADA		= PMUDSITUACAO.CODCOLIGADA
													AND	VCHAPAATESTADO.MOTIVOAFAST		= PMUDSITUACAO.CODCLIENTE
WHERE
		PFUNC.CHAPA = '003938'

ORDER BY
	VCHAPAATESTADO.DTINICIO ASC