SET DATEFORMAT DMY;
SET LANGUAGE 'BRAZILIAN';

SELECT
	 PFUNC.CHAPA
	,PFUNC.CODFUNCAO
	,PFUNCAO.NOME
	,PFUNC.CODFILIAL
	,PFUNC.NOME
	,MATRICULA = PPESSOA.CODUSUARIO
	,CPF =	CONCAT	(	SUBSTRING(PPESSOA.CPF,1,3), '.',
						SUBSTRING(PPESSOA.CPF,4,3), '.',
						SUBSTRING(PPESSOA.CPF,7,3), '-',
						SUBSTRING(PPESSOA.CPF,10,2)
					)
	,PFUNC.PISPASEP
	,ADMISSAO = CONVERT(VARCHAR, PFUNC.DATAADMISSAO, 103)
	,DEMISSAO = CONVERT(VARCHAR, PFUNC.DATADEMISSAO, 103)
	,PFUNC.TIPODEMISSAO
	,PTPDEMISSAO.DESCRICAO
	,DATAEVENTO = CONVERT(VARCHAR, PESOCIALEVENTOS.DATAEVENTO, 103)
	,PESOCIALEVENTOS.TIPOEVENTO
	,PESOCIALEVENTOS.ID
	,PESOCIALEVENTOS.LOGGERACAO
	,ENVIO = CONVERT(VARCHAR, PESOCIALEVENTOS.DATAENVIO, 103)
	,DISPONIVEL = CONVERT(VARCHAR, PESOCIALEVENTOS.DATAENVIO +6, 103)
	,PESOCIALEVENTOS.STATUS
	,STATUS_DESC = CASE	WHEN PESOCIALEVENTOS.STATUS = 0  THEN 'PENDENTE'
						WHEN PESOCIALEVENTOS.STATUS = 1  THEN 'GERADO'
						WHEN PESOCIALEVENTOS.STATUS = 2  THEN 'ERRO NA GERAÇÃO'
						WHEN PESOCIALEVENTOS.STATUS = 3  THEN 'ENVIADO'
						WHEN PESOCIALEVENTOS.STATUS = 4  THEN 'ACEITO'
						WHEN PESOCIALEVENTOS.STATUS = 5  THEN 'ERRO NA INTEGRAÇÃO'
						WHEN PESOCIALEVENTOS.STATUS = 6  THEN 'REJEITADO TAF'
						WHEN PESOCIALEVENTOS.STATUS = 7  THEN 'CANCELADO'
						WHEN PESOCIALEVENTOS.STATUS = 8  THEN 'RETIFICADO'
						WHEN PESOCIALEVENTOS.STATUS = 9  THEN 'REJEITADO RET'
						WHEN PESOCIALEVENTOS.STATUS = 10 THEN 'ACEITO RET'
						WHEN PESOCIALEVENTOS.STATUS = 11 THEN 'EXCLUIDO RET'
						ELSE 'STATUS NOVO. CONTACTAR DIT'
					END	
	,HOJE = FORMAT(GETDATE(), 'DDDD, D \DE MMMM \DE YYYY', 'PT-BR')
	,PPESSOA.CIDADE
	,GFILIAL.NOME																																	[FILIAL_NOME]
	,GFILIAL.CGC			 																															[CNPJ_FILIAL]
	,'CNPJ: ' + GFILIAL.CGC  																														[CNPJ_FILIAL2]
	,GFILIAL.RUA + ', Nº ' + GFILIAL.NUMERO + ', ' + GFILIAL.BAIRRO + ', ' + GFILIAL.ESTADO															[ENDERECO]
	,UPPER(GFILIAL.CIDADE) + ', CEP: ' + ( SUBSTRING(GFILIAL.CEP, 1, 2) + '.' + SUBSTRING(GFILIAL.CEP, 3, 3) + '-' + SUBSTRING(GFILIAL.CEP, 6, 3))	[CIDADE_CEP]
	,GFILIAL.CIDADE
	,GFILIAL.CEP                                                                                                                                    	[CEP_FILIAL]
	,GIMAGEM.IMAGEM																																	[IMAGEM_FILIAL] 
	,GFILIAL.CIDADE + ' - ' + GFILIAL.ESTADO                                                                                                         [CIDADE_UF]
FROM
					GCOLIGADA		(NOLOCK)
	INNER	JOIN	GFILIAL			(NOLOCK) ON	GCOLIGADA.CODCOLIGADA	= GFILIAL.CODCOLIGADA
	INNER	JOIN	GIMAGEM		    (NOLOCK) ON	GIMAGEM.ID				= GFILIAL.IDIMAGEM
	INNER	JOIN	PFUNC			(NOLOCK) ON	GFILIAL.CODCOLIGADA		= PFUNC.CODCOLIGADA AND GFILIAL.CODFILIAL = PFUNC.CODFILIAL
	LEFT	JOIN	PFUNCAO			(NOLOCK) ON	PFUNC.CODCOLIGADA		= PFUNCAO.CODCOLIGADA AND PFUNC.CODFUNCAO = PFUNCAO.CODIGO
	INNER	JOIN	PTPDEMISSAO		(NOLOCK) ON	PFUNC.TIPODEMISSAO		= PTPDEMISSAO.CODCLIENTE
	INNER	JOIN	PPESSOA			(NOLOCK) ON	PFUNC.CODPESSOA			= PPESSOA.CODIGO
	INNER	JOIN	PESOCIALEVENTOS	(NOLOCK) ON	PFUNC.CODCOLIGADA		= PESOCIALEVENTOS.CODCOLIGADA	AND PFUNC.CHAPA	= PESOCIALEVENTOS.CHAPA
WHERE
    PESOCIALEVENTOS.TIPOEVENTO 							= 'S-2299'
    AND PFUNC.CODCOLIGADA 								= 2
    AND CONVERT(VARCHAR, PFUNC.DATADEMISSAO, 103)		= '04/03/2024'
    AND	PFUNC.TIPODEMISSAO								IN ('2', 'T', 'V')
	AND PFUNC.CODFILIAL									= GFILIAL.CODFILIAL
	
	