SELECT DISTINCT
 DLAF.CODCOLIGADA,
 COLIGADA = CASE WHEN DLAF.CODCOLIGADA = 1 THEN 'UNICEUMA'
					WHEN DLAF.CODCOLIGADA = 2 THEN 'UNIEURO'
				END,
 DLAF.CODFILIAL,
 FILIAL = GFILIAL.NOMEFANTASIA,
 DLAF.IDLAF,
 DLAF.IDLAFAGRUP,
 DTRBITEM.IDTRBITEM,
 DLAF.DATAEMISSAO,
 DLAF.CODCFO,
 FORNECEDOR = FCFO.NOMEFANTASIA,
 FORNECEDOR_IDNAT = FCFO.IDNATRENDIMENTO,
 DTRBLAF.CODTRB,
 
 DTRBLAF_IDNAT = DTRBLAF.IDNATRENDIMENTO,
  DTRBLAFITEM_IDNAT = DTRBITEM.IDNATRENDIMENTO,
  DLAF.DOCINI,
  DLAFAGRUP.VALORCONT

FROM
	DLAFAGRUP (NOLOCK)
		JOIN DLAF (NOLOCK)
			ON DLAF.CODCOLIGADA = DLAFAGRUP.CODCOLIGADA
				AND DLAF.IDLAFAGRUP = DLAFAGRUP.IDLAFAGRUP
		JOIN FCFO (NOLOCK)
			ON FCFO.CODCFO = DLAF.CODCFO
		JOIN DTRBLAF (NOLOCK)
			ON DTRBLAF.CODCOLIGADA = DLAF.CODCOLIGADA
				AND DTRBLAF.IDLAF	= DLAF.IDLAF
		JOIN DTRBITEM (NOLOCK)
			ON DTRBITEM.CODCOLIGADA = DLAF.CODCOLIGADA
				AND DTRBITEM.IDLAF = DLAF.IDLAF
		JOIN GFILIAL (NOLOCK)
			ON GFILIAL.CODCOLIGADA = DLAF.CODCOLIGADA
				AND GFILIAL.CODFILIAL =DLAF.CODFILIAL

	
WHERE
	1 = 1
	AND DLAFAGRUP.CODCOLIGADA IN (1,2)
	AND YEAR(DLAF.DATAEMISSAO) = :ANO
	AND MONTH(DLAF.DATAEMISSAO) = :MES
	AND DTRBLAF.CODTRB IN ('PCC','IRRFPJ')