SELECT DISTINCT
	TMOV.CODCOLIGADA,
	COLIGADA = CASE WHEN TMOV.CODCOLIGADA = 1 THEN 'UNICEUMA'
					WHEN TMOV.CODCOLIGADA = 2 THEN 'UNIEURO'
				END,
	TMOV.CODFILIAL,
	FILIAL = GFILIAL.NOMEFANTASIA,
	TMOV.DATAEMISSAO,
	TMOV.CODTMV,
	TMOV.IDMOV,
	TMOV.NUMEROMOV,
	TMOV.VALORBRUTO,
	TMOV.CODCFO,
	FORNECEDOR = FCFO.NOMEFANTASIA,
	TRIBUTO_MOV_CODTRB = TTRBMOV.CODTRB,
	FCFO_IDNAT = FCFO.IDNATRENDIMENTO,
	TRIBUTO_MOV_IDNAT = TTRBMOV.IDNATRENDIMENTO,
	TPRD.CODIGOPRD,
	TPRD.IDPRD,
	PRODUTO_NOME = TPRD.NOMEFANTASIA,
	PRODUTO_IDNAT = TPRDFISCAL.IDNATRENDIMENTO,
	QTDE = 1

FROM
	TMOV (NOLOCK)
		JOIN TTRBMOV (NOLOCK)
			on TTRBMOV.CODCOLIGADA = TMOV.CODCOLIGADA
				AND TTRBMOV.IDMOV = TMOV.IDMOV
		JOIN FCFO (NOLOCK)
			ON FCFO.CODCFO = TMOV.CODCFO
		JOIN TITMMOV (NOLOCK)
			ON TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA
				AND TITMMOV.IDMOV = TMOV.IDMOV
		JOIN TPRD (NOLOCK)
			ON TPRD.CODCOLIGADA = TITMMOV.CODCOLIGADA
				AND TPRD.IDPRD = TITMMOV.IDPRD
		JOIN TPRDFISCAL (NOLOCK)
			ON TPRDFISCAL.CODCOLIGADA = TPRD.CODCOLIGADA
				AND TPRDFISCAL.IDPRD = TPRD.IDPRD
		JOIN GFILIAL (NOLOCK)
			ON GFILIAL.CODCOLIGADA = TMOV.CODCOLIGADA
				AND GFILIAL.CODFILIAL = TMOV.CODFILIAL
		
WHERE
	1 = 1
	AND TMOV.CODCOLIGADA in (1,2)
	AND TTRBMOV.CODTRB IN ('IRRFPJ')
	AND YEAR(TMOV.DATAEMISSAO) = :ANO
	AND MONTH(TMOV.DATAEMISSAO) = :MES
	AND TTRBMOV.ALIQUOTA > 0