SELECT 
	 'DATA CRIAÇÃO'		=	CONVERT(VARCHAR, TMOV.RECCREATEDON, 103)
	,'COLIGADA'			=	TMOV.CODCOLIGADA
	,'FILIAL'			=	TMOV.CODFILIAL
	,'ID MOVIMENTO'		=	TMOV.IDMOV
	,'COD NATUREZA'		=	TTBORCAMENTO.CODTBORCAMENTO
	,'NATUREZA ORÇ'		=	TTBORCAMENTO.DESCRICAO
	,'CODIGO MOV'		=	TMOV.CODTMV
	,'NOME MOVIMENTO'	=	TTMV.NOME
	,'COD ALMOX'		=	TMOV.CODLOC
	,'ALMOXARIFADO'		=	TLOC.NOME
	,'CENT. CUSTO'		=	GCCUSTO.NOME
	
	--,TMOV.*
FROM 
				 TMOV		(NOLOCK)
	INNER	JOIN TTMV		(NOLOCK) ON TMOV.CODCOLIGADA = TTMV.CODCOLIGADA AND TMOV.CODTMV = TTMV.CODTMV
	LEFT	JOIN GCCUSTO	(NOLOCK) ON TMOV.CODCOLIGADA = GCCUSTO.CODCOLIGADA AND TMOV.CODCCUSTO = GCCUSTO.CODCCUSTO
	INNER	JOIN TITMMOV	(NOLOCK) ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA AND TMOV.IDMOV = TITMMOV.IDMOV
	INNER	JOIN TLOC		(NOLOCK) ON TITMMOV.CODCOLIGADA = TLOC.CODCOLIGADA AND TITMMOV.CODFILIAL = TLOC.CODFILIAL AND TITMMOV.CODLOC = TLOC.CODLOC
	INNER	JOIN TPRODUTO	(NOLOCK) ON TITMMOV.IDPRD = TPRODUTO.IDPRD
	INNER	JOIN TPRODUTODEF(NOLOCK) ON TPRODUTO.IDPRD = TPRODUTODEF.IDPRD
	INNER	JOIN TTBORCAMENTO(NOLOCK)ON TPRODUTODEF.CODCOLTBORCAMENTO = TTBORCAMENTO.CODCOLIGADA AND TPRODUTODEF.CODTBORCAMENTO = TTBORCAMENTO.CODTBORCAMENTO
WHERE 
		
--		TMOV.IDMOV = '574357'
		TMOV.CODTMV = '1.1.18'
--		TMOV.RECCREATEDBY = '2-003703'

--			TTBORCAMENTO.DESCRICAO LIKE '%PASSAGENS AÉREAS%'
		AND TMOV.CODCOLIGADA = 2
		AND TMOV.CODFILIAL = 2
--		AND TMOV.RECCREATEDBY = '2-003703'
ORDER BY TMOV.RECCREATEDON DESC

/* 
*/
--SELECT * FROM TTMV