SELECT DISTINCT
	FLAN.CODCOLIGADA,
	COLIGADA = CASE WHEN FLAN.CODCOLIGADA = 1 THEN 'UNICEUMA'
					WHEN FLAN.CODCOLIGADA = 2 THEN 'UNIEURO'
				END,
	FLAN.CODFILIAL,
	FILIAL = GFILIAL.NOMEFANTASIA,
	FLAN.IDLAN,
	FLAN.NUMERODOCUMENTO,
	FLAN.DATABAIXA,
	FLAN.CODCFO,
	FORNECEDOR = FCFO.NOMEFANTASIA,
	TRIBUTO_FLAN_CODTRB = FTRBLAN.CODTRB,
	FCFO_IDNAT = FCFO.IDNATRENDIMENTO,
	TRIBUTO_FLAN_IDNAT = FTRBLAN.IDNATRENDIMENTO,
	FLAN.VALORORIGINAL,

	QTDE = 1

FROM
	FLAN(NOLOCK)
		JOIN FTRBLAN (NOLOCK)
			ON FTRBLAN.CODCOLIGADA = FLAN.CODCOLIGADA
				AND FTRBLAN.IDLAN = FLAN.IDLAN
		JOIN FCFO (NOLOCK)
			ON FCFO.CODCFO = FLAN.CODCFO
		JOIN GFILIAL (NOLOCK)
			ON GFILIAL.CODCOLIGADA = FLAN.CODCOLIGADA
				AND GFILIAL.CODFILIAL = FLAN.CODFILIAL
		


WHERE
	1 = 1
	AND FLAN.CODCOLIGADA IN (1,2)
	AND FTRBLAN.CODTRB IN ('PCC')
	AND YEAR(FLAN.DATABAIXA) = :ANO
	AND MONTH(FLAN.DATABAIXA) = :MES
	AND FTRBLAN.ALIQUOTA > 0