--					SELECT * FROM GLINKSREL WHERE CHILDTABLE = 'QCUBOX'
DECLARE 
	@USUARIO VARCHAR(8)	='1-004625',
	@COLIGADA VARCHAR (1)	= '1',
	@CHAPAATENDENTE VARCHAR (6) = '004625'

SELECT 
		GUSRPERFIL.CODCOLIGADA		AS [COLIGADA], 
		GSISTEMA.NOMESISTEMA		AS [SISTEMA],
		GSISTEMA.CODSISTEMA			AS [CÓD],
		GSISTEMA.DESCRICAO			AS [MÓDULO],
		GPERFIL.IDPERFIL			AS [PERFIL],
		GPERMIS.SUPERVISOR			AS SUPERVISOR,
		QCATCUBOPERFIL.CODPERFIL	AS PERM_CUBO,
		QCUBOX.IDCATEGORIA			AS CATEGORIA



FROM 	
	GPERFIL 
	INNER JOIN GUSRPERFIL (NOLOCK)	ON GPERFIL.CODSISTEMA = GUSRPERFIL.CODSISTEMA 	AND GPERFIL.CODPERFIL = GUSRPERFIL.CODPERFIL
	INNER JOIN GPERMIS (NOLOCK) ON GUSRPERFIL.CODCOLIGADA = GPERMIS.CODCOLIGADA	AND GUSRPERFIL.CODSISTEMA = GPERMIS.CODSISTEMA
		AND GUSRPERFIL.CODUSUARIO = GPERMIS.CODUSUARIO	INNER JOIN GSISTEMA (NOLOCK) 
		ON GUSRPERFIL.CODSISTEMA = GSISTEMA.CODSISTEMA	INNER JOIN QCATCUBOPERFIL (NOLOCK)
		ON GPERFIL.CODSISTEMA = QCATCUBOPERFIL.CODSISTEMAPERFIL	AND GPERFIL.CODPERFIL = QCATCUBOPERFIL.CODPERFIL
	INNER JOIN QCATEGORIACUBO (NOLOCK)		ON QCATCUBOPERFIL.IDCATEGORIA = QCATEGORIACUBO.ID
	LEFT JOIN QCUBOX (NOLOCK)		ON QCATEGORIACUBO.ID = QCUBOX.IDCATEGORIA
WHERE 
		GUSRPERFIL.CODUSUARIO = @USUARIO
		AND GUSRPERFIL.CODCOLIGADA = @COLIGADA
		AND QCUBOX.NOME LIKE 'GCORÇ014.004 - GESTÃO ORÇAMENTARIA'