SET DATEFORMAT DMY;
SET LANGUAGE 'BRAZILIAN';

WITH
  VIEWFUNCIONARIOS AS (
    SELECT
        PF.CODCOLIGADA, PF.CHAPA, PF.CODFILIAL, PF.NOME AS 'FUNCIONARIO', PF.CODSITUACAO, PF.SALARIO, PF.CODSECAO
      , JORNADAMENSAL = (CONVERT(FLOAT, (PF.JORNADAMENSAL/60)) )
      , PPPF.CPF, PPPF.DTNASCIMENTO, PPPF.CODIGO, PF.CODPESSOA
      , PFC.NOME AS 'CARGO', PS.DESCRICAO AS 'SETOR'
    FROM PFUNC AS PF (NOLOCK)
    INNER JOIN PPESSOA AS PPPF (NOLOCK) ON (PPPF.CODIGO = PF.CODPESSOA)
    INNER JOIN PFUNCAO AS PFC (NOLOCK) ON (PFC.CODCOLIGADA = PF.CODCOLIGADA) AND (PFC.CODIGO = PF.CODFUNCAO)
    INNER JOIN PSECAO AS PS (NOLOCK) ON (PS.CODCOLIGADA = PF.CODCOLIGADA) AND (PS.CODIGO = PF.CODSECAO)
 )
  , VIEWEVENTOS AS (
     SELECT
        PE.CODCOLIGADA, PE.INCSALFAMILIA, PE.CODIGO, PE.PROVDESCBASE, PE.DESCRICAO, PE.VALHORDIAREF, PE.INCFGTS, PE.INCFGTS13, PE.INCIRRF, PE.INCDSR
      , PE.INCTERCOFERIAS, PE.CONTACREDITO, PE.CONTADEBITO, PE.TEMINTCONTCC, PE.TEMINTCONTCD
      , PFF.ANOCOMP, PFF.MESCOMP, PFF.CHAPA, PFF.REF, PFF.CODEVENTO AS 'EVENTO', PFF.VALOR

     FROM PEVENTO AS PE (NOLOCK)
     INNER JOIN PFFINANC AS PFF (NOLOCK) ON (PFF.CODCOLIGADA = PE.CODCOLIGADA) AND (PFF.CODEVENTO = PE.CODIGO)
  )
  , VIEWCOLIGADA AS (
     SELECT
         GCOLIGADA.CODCOLIGADA, GCOLIGADA.CGC AS 'CNPJ', GCOLIGADA.NOME AS 'EMPRESA', GFILIAL.CGC AS 'CNPJ2', GFILIAL.NOME AS 'FILIAL', GFILIAL.CODFILIAL
     FROM GCOLIGADA (NOLOCK)
     INNER JOIN GFILIAL (NOLOCK) ON (GFILIAL.CODCOLIGADA = GCOLIGADA.CODCOLIGADA)
  )
 , VIEWTOTAIS AS
	(	SELECT
			 TOTAL_FUNC	=	(SELECT COUNT(PFUNC.CHAPA) FROM PFUNC(NOLOCK) INNER JOIN PPESSOA ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE PFUNC.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1 AND PFUNC.CODSITUACAO <> 'D'	)
			,HOMENS		=	(	SELECT COUNT(PFUNC.CHAPA) FROM PFUNC(NOLOCK) INNER JOIN PPESSOA ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE PFUNC.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1 AND PFUNC.CODSITUACAO <> 'D' AND PPESSOA.SEXO = 'M'	)
			,MULHERES	=	(	SELECT COUNT(PFUNC.CHAPA) FROM PFUNC(NOLOCK) INNER JOIN PPESSOA ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE PFUNC.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1 AND PFUNC.CODSITUACAO <> 'D' AND PPESSOA.SEXO = 'F'	)
			,PFUNC.CODCOLIGADA
			,PFUNC.CODFILIAL
			,PFUNC.CHAPA
			,PFUNC.CODSITUACAO
		FROM
			PFUNC
		GROUP BY PFUNC.CODCOLIGADA ,PFUNC.CODFILIAL ,PFUNC.CHAPA ,PFUNC.CODSITUACAO
	)
 , VIEWACIDENTES AS
	(	SELECT
			 VOCORRENCIA.CODCOLIGADA,VOCORRENCIA.CID,VOCORRENCIA.NUMEROCAT,VOCORRENCIA.CODOCORRENCIA,VOCORRENCIA.CHAPA,PPESSOA.NOME,VOCORRENCIA.REGISTROINSS
			,VOCORRENCIA.HORASTRAB,CONVERT(VARCHAR, VOCORRENCIA.DATAHORA, 103)	AS DATAHORA,VOCORRENCIA.DESCRICAO,VOCORRENCIA.LOCALACIDENTE
			,VPPRAFONTEGERA.NOME AS SIT_GERADORA,VCODACTRABALHO.DESCRICAO AS ACID_ESOCIAL  
		FROM VOCORRENCIA
			INNER JOIN PFUNC ON PFUNC.CHAPA = VOCORRENCIA.CHAPA AND PFUNC.CODCOLIGADA = VOCORRENCIA.CODCOLIGADA
			INNER JOIN PPESSOA ON PPESSOA.CODIGO = PFUNC.CODPESSOA
			INNER JOIN VTIPOOCORRENCIA ON VTIPOOCORRENCIA.CODTIPOOCORRENCIA = VOCORRENCIA.CODTIPOOCORRENCIA
			INNER JOIN VPPRAFONTEGERA ON VPPRAFONTEGERA.CODFONTEGERA = VOCORRENCIA.CODSITUACAOGERA
			LEFT JOIN VCODACTRABALHO ON VCODACTRABALHO.CODCLIENTE = VOCORRENCIA.TIPOACIDENTEESOCIAL

		WHERE
			YEAR(VOCORRENCIA.DATAHORA) = '2023'	AND PFUNC.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1
	)
 , VIEWMESESATESTADO AS
	(	SELECT DISTINCT
			 PFUNC.CODCOLIGADA
			,PFUNC.CODFILIAL
			,TOTAL_ATESTADO		= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,JANEIRO	= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 01 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,FEVEREIRO	= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 02 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,MARCO		= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 03 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,ABRIL		= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 04 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,MAIO		= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 05 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,JUNHO		= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 06 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,JULHO		= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 07 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,AGOSTO		= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 08 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,SETEMBRO	= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 09 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,OUTUBRO	= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 10 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,NOVEMBRO	= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 11 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
			,DEZEMBRO	= (SELECT COUNT(SEQATESTADO) FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND MONTH(VATESTADO.DTINICIO) = 12 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1)
		FROM VATESTADO	INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO
	)
 , VIEWCIDREINCIDENTE AS
	(	SELECT DISTINCT TOP 5 COD_CID = VATESTADO.CID, TOT_CID = COUNT(VATESTADO.CID), PFUNC.CODCOLIGADA, PFUNC.CODFILIAL 
		FROM VATESTADO INNER JOIN PPESSOA(NOLOCK) ON VATESTADO.CODPESSOA = PPESSOA.CODIGO INNER JOIN PFUNC(NOLOCK) ON PFUNC.CODPESSOA = PPESSOA.CODIGO 
		WHERE YEAR(VATESTADO.DTINICIO) = 2023 AND VATESTADO.CODCOLIGADA = 1 AND PFUNC.CODFILIAL = 1 
		GROUP BY VATESTADO.CID, PFUNC.CODCOLIGADA, PFUNC.CODFILIAL 
		ORDER BY TOT_CID DESC
	)
 , VIEWFINAL AS (
    SELECT
        VIEWFUNCIONARIOS.*
      , VIEWCOLIGADA.CNPJ, VIEWCOLIGADA.EMPRESA, VIEWCOLIGADA.CNPJ2, VIEWCOLIGADA.FILIAL
      , VIEWEVENTOS.REF AS 'DIASATESTADO', VIEWEVENTOS.EVENTO, VIEWEVENTOS.ANOCOMP, VIEWEVENTOS.MESCOMP, VIEWEVENTOS.VALOR
	  , VIEWTOTAIS.TOTAL_FUNC, VIEWTOTAIS.HOMENS, VIEWTOTAIS.MULHERES
	  , VIEWACIDENTES.DESCRICAO AS ACIDENTE, VIEWACIDENTES.CID, VIEWACIDENTES.NUMEROCAT, (SELECT COUNT(VIEWACIDENTES.CHAPA) FROM VIEWACIDENTES) AS QTD_ACIDENTE
	  ,VIEWMESESATESTADO.TOTAL_ATESTADO,VIEWMESESATESTADO.JANEIRO ,VIEWMESESATESTADO.FEVEREIRO ,VIEWMESESATESTADO.MARCO ,VIEWMESESATESTADO.ABRIL ,VIEWMESESATESTADO.MAIO ,VIEWMESESATESTADO.JUNHO
	  ,VIEWMESESATESTADO.JULHO ,VIEWMESESATESTADO.AGOSTO ,VIEWMESESATESTADO.SETEMBRO ,VIEWMESESATESTADO.OUTUBRO ,VIEWMESESATESTADO.NOVEMBRO ,VIEWMESESATESTADO.DEZEMBRO
	  , VIEWCIDREINCIDENTE.COD_CID, VIEWCIDREINCIDENTE.TOT_CID

    FROM		 VIEWFUNCIONARIOS
    INNER	JOIN VIEWCOLIGADA		ON (VIEWCOLIGADA.CODCOLIGADA		= VIEWFUNCIONARIOS.CODCOLIGADA)		AND (VIEWCOLIGADA.CODFILIAL			= VIEWFUNCIONARIOS.CODFILIAL)
    INNER	JOIN VIEWEVENTOS		ON (VIEWEVENTOS.CODCOLIGADA			= VIEWFUNCIONARIOS.CODCOLIGADA)		AND (VIEWEVENTOS.CHAPA				= VIEWFUNCIONARIOS.CHAPA)
	INNER	JOIN VIEWTOTAIS			ON (VIEWTOTAIS.CODCOLIGADA			= VIEWFUNCIONARIOS.CODCOLIGADA)		AND (VIEWTOTAIS.CHAPA				= VIEWFUNCIONARIOS.CHAPA)
	LEFT	JOIN VIEWACIDENTES		ON (VIEWFUNCIONARIOS.CHAPA			= VIEWACIDENTES.CHAPA)				AND (VIEWFUNCIONARIOS.CODCOLIGADA	= VIEWACIDENTES.CODCOLIGADA)
	LEFT	JOIN VIEWMESESATESTADO	ON (VIEWFUNCIONARIOS.CODCOLIGADA	= VIEWMESESATESTADO.CODCOLIGADA)	AND (VIEWFUNCIONARIOS.CODFILIAL		= VIEWMESESATESTADO.CODFILIAL)
	LEFT	JOIN VIEWCIDREINCIDENTE ON (VIEWFUNCIONARIOS.CODCOLIGADA	= VIEWCIDREINCIDENTE.CODCOLIGADA)	AND (VIEWFUNCIONARIOS.CODFILIAL		= VIEWCIDREINCIDENTE.CODFILIAL)
 )

SELECT
    cast(FILIAL as varchar), CODCOLIGADA, CODFILIAL, CHAPA, FUNCIONARIO, CODSECAO, SETOR
  , JORNADAMENSAL, CONVERT(INT, DIASATESTADO) AS DIASATESTADO
  , CAST( CONVERT(FLOAT, ( ( JORNADAMENSAL / 25 ) * DIASATESTADO )) AS DECIMAL(16,2) ) AS 'HR. ATESTADO'
  , VALOR = CAST( ( (SALARIO / 30) * DIASATESTADO ) AS NUMERIC(16,2) )
  , TOTAL_FUNC,	HOMENS, MULHERES, CODSITUACAO
  ,QTD_ACIDENTE, ACIDENTE, CID, NUMEROCAT
  ,TOTAL_ATESTADO,JANEIRO ,FEVEREIRO ,MARCO ,ABRIL ,MAIO ,JUNHO ,JULHO ,AGOSTO ,SETEMBRO ,OUTUBRO ,NOVEMBRO ,DEZEMBRO
  ,COD_CID, TOT_CID

FROM VIEWFINAL 
WHERE EVENTO = '0215' AND ANOCOMP = 2023 AND CODCOLIGADA = 1 AND CODFILIAL = 1 and CODSITUACAO <> 'D'
ORDER BY FILIAL, FUNCIONARIO


