SELECT
	TITMMOV.CODCOLIGADA,
	TITMMOV.CODFILIAL,
	CONVERT(VARCHAR, TITMMOV.DATAORCAMENTO, 103)								AS 'DATAORCAMENTO',
	TITMMOV.CODCCUSTO,
	TITMMOV.CODTBORCAMENTO,
	TITMMOV.IDMOV,
	TITMMOV.IDPRD,
	TMOV.CODTMV,
	CASE 
        WHEN TITMTMV.EFEITOSALDOORCA = 'T' THEN 'AUMENTA O COMPROMETIDO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'N' THEN 'NENHUM EFEITO NO ORÇAMENTO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'M' THEN 'AUMENTA O EMPENHADO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'D' THEN 'DIMINUI O REALIZADO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'A' THEN 'AUMENTA O REALIZADO' 
	END																			AS 'EFEITO NO SALDO DO ORÇAMENTO',
	TITMMOV.VALORTOTALITEM,
	TITMMOV.VALORCONCLUIDO,
	TITMMOV.RATEIOCCUSTODEPTO,
	TMOV.VALORBRUTOINTERNO,
	TITMMOV.VALORLIQUIDO,
	CASE WHEN TITMMOV.VALORLIQUIDO <> TITMMOV.RATEIOCCUSTODEPTO THEN 'DIFERENTE' ELSE 'IGUAL' END AS 'VALIDADOR'
FROM 
				TITMMOV
	JOIN		TMOV			(NOLOCK) ON TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOV.IDMOV = TMOV.IDMOV
	JOIN		TTMV			(NOLOCK) ON	TMOV.CODCOLIGADA = TTMV.CODCOLIGADA AND	TMOV.CODTMV	= TTMV.CODTMV
	JOIN		TTMVEXT			(NOLOCK) ON TTMV.CODCOLIGADA = TTMVEXT.CODCOLIGADA AND TTMV.CODTMV = TTMVEXT.CODTMV
	JOIN		TITMTMV			(NOLOCK) ON TITMTMV.CODCOLIGADA = TTMVEXT.CODCOLIGADA AND TITMTMV.CODTMV = TTMVEXT.CODTMV
	
--	JOIN		TMOVORCAMENTO	(NOLOCK) ON TMOV.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA AND TMOV.IDMOV = TMOVORCAMENTO.IDMOV


WHERE
		1=1
	AND TITMTMV.CODCOLIGADA = 2
	AND YEAR(TITMMOV.DATAORCAMENTO) = 2024
	AND MONTH(TITMMOV.DATAORCAMENTO) IN (1,2,3,4,5)
	AND TITMTMV.CODTMV IN (	'1.2.11', '1.2.12', '1.2.20', '1.2.21', '1.2.22', '1.2.23', '1.2.24', '1.2.25', '1.2.27', '1.2.28', '1.2.29', '1.2.31'	)
--	AND TITMTMV.EFEITOSALDOORCA <> 'A'
--	AND TITMTMV.EFEITOSALDOORCA <> 'T'
	AND TITMTMV.EFEITOSALDOORCA = 'N'
ORDER BY
	TITMMOV.CODCOLIGADA,
	TITMMOV.CODFILIAL,
	TITMMOV.DATAORCAMENTO ASC

