 SELECT DISTINCT
	TMOVORCAMENTO.CODCOLIGADA																																	AS 'CODCOLIGADA',
	TMOV.CODFILIAL																																				AS	'CODFILIAL',
	TITMMOV.CODCCUSTO																																			AS 'CC',
	TITMMOV.CODTBORCAMENTO																																		AS 'COD_NATUREZA',
	TMOVORCAMENTO.IDITMPERIODO																																	AS 'IDITMPERIODO',
	TMOVORCAMENTO.IDPERIODO																																		AS 'IDPERIODO',
	TITMTMV.CODTMV																																				AS 'CODTMV', 
	TMOVORCAMENTO.IDORCAMENTO																																	AS 'IDORCAMENTO',
	TMOV.IDMOV																																					AS 'IDMOV',
	TMOVORCAMENTO.VALOROPCIONAL2																																AS 'COMPROMETIDO_TMOVORCAMENTO',
	CASE 
        WHEN TITMTMV.EFEITOSALDOORCA = 'T' THEN 'AUMENTA O COMPROMETIDO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'N' THEN 'NENHUM EFEITO NO ORÇAMENTO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'M' THEN 'AUMENTA O EMPENHADO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'D' THEN 'DIMINUI O REALIZADO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'A' THEN 'AUMENTA O REALIZADO' 
    END																																							AS 'EFEITO',
    CASE WHEN TTMVEXT.BUSCARNATORCDEFAULTPRD = 'D' THEN 'DESPESA' 
		 WHEN TTMVEXT.BUSCARNATORCDEFAULTPRD = 'R' THEN 'RECEITA' 
		 ELSE TTMVEXT.BUSCARNATORCDEFAULTPRD							
	END																																							AS 'BUSCAR DEFAULT DO PRODUTO',
	 CASE 
        WHEN TITMTMV.LIMESTOUROORCAMENTO = 'A' THEN 'AVISA' 
        WHEN TITMTMV.LIMESTOUROORCAMENTO = 'L' THEN 'BLOQUEIA' 
    END																																							AS 'LIMITE DE ESTOURO DO ORÇAMENTO',
	CASE TTMV.CONTABILLAN
		WHEN 'N' THEN 'Nâo Contábil'
		WHEN 'B' THEN 'Baixa Contábil'
		WHEN 'C' THEN 'Contábil'
		WHEN 'A' THEN 'A Contabilizar'
		ELSE 'Sem parametrização'
	END																																							AS 'CONT_FINANCEIRO'

FROM 
					TMOVORCAMENTO	(NOLOCK)
	JOIN			TITMORCAMENTO	(NOLOCK) ON TITMORCAMENTO.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA AND TITMORCAMENTO.IDORCAMENTO = TMOVORCAMENTO.IDORCAMENTO AND TITMORCAMENTO.IDITMPERIODO = TMOVORCAMENTO.IDITMPERIODO AND TITMORCAMENTO.IDPERIODO = TMOVORCAMENTO.IDPERIODO
	JOIN			TORCAMENTO		(NOLOCK) ON TORCAMENTO.CODCOLIGADA = TITMORCAMENTO.CODCOLIGADA AND TORCAMENTO.IDPERIODO = TITMORCAMENTO.IDPERIODO AND TORCAMENTO.IDORCAMENTO = TITMORCAMENTO.IDORCAMENTO
	JOIN			TMOV			(NOLOCK) ON TMOV.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA AND TMOV.IDMOV = TMOVORCAMENTO.IDMOV
	JOIN			TITMMOV			(NOLOCK) ON TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOV.IDMOV = TMOV.IDMOV
	JOIN			GCCUSTO			(NOLOCK) ON GCCUSTO.CODCOLIGADA = TITMMOV.CODCOLIGADA AND GCCUSTO.CODCCUSTO = TITMMOV.CODCCUSTO
	JOIN			GFILIAL			(NOLOCK) ON	TMOV.CODCOLIGADA = GFILIAL.CODCOLIGADA AND	TMOV.CODFILIAL = GFILIAL.CODFILIAL
	JOIN			TTMV			(NOLOCK) ON	TMOV.CODCOLIGADA = TTMV.CODCOLIGADA AND	TMOV.CODTMV	= TTMV.CODTMV
	JOIN			TTMVEXT			(NOLOCK) ON TTMV.CODCOLIGADA = TTMVEXT.CODCOLIGADA AND TTMV.CODTMV = TTMVEXT.CODTMV
	JOIN			TITMTMV			(NOLOCK) ON TITMTMV.CODCOLIGADA = TTMVEXT.CODCOLIGADA AND TITMTMV.CODTMV = TTMVEXT.CODTMV
	LEFT JOIN		TMOTIVOREFMOV	(NOLOCK) ON TMOTIVOREFMOV.CODCOLIGADA = TTMVEXT.CODCOLIGADA AND TMOTIVOREFMOV.IDMOTIVOREF = TTMVEXT.IDMOTIVOREF

WHERE 
		1=1
	--AND TITMTMV.CODCOLIGADA IN (1, 2)
	AND TITMTMV.CODTMV LIKE '1.2.%'
	AND TITMTMV.EFEITOSALDOORCA <> 'A'
--	AND TMOV.IDMOV = 585737
	AND TMOVORCAMENTO.VALOROPCIONAL2 > 0

--SELECT CODCOLIGADA, IDMOVORCAMENTO, IDMOV, TIPO,IDORCAMENTO, IDPERIODO, IDITMPERIODO, VALOROPCIONAL2 FROM TMOVORCAMENTO WHERE CODCOLIGADA = 1 AND IDMOVORCAMENTO = 929920 AND IDMOV = 583569 AND TIPO = 'I' AND IDORCAMENTO = 316338 AND IDPERIODO = 24 AND IDITMPERIODO = 5 AND VALOROPCIONAL2 = 1020.8000;

/*
BEGIN TRANSACTION
	UPDATE TMOVORCAMENTO SET VALOROPCIONAL2 = 0 WHERE CODCOLIGADA = 1 AND IDMOVORCAMENTO = 929920 AND IDMOV = 583569 AND TIPO = 'I' AND IDORCAMENTO = 316338 AND IDPERIODO = 24 AND IDITMPERIODO = 5 AND VALOROPCIONAL2 = 1020.8000
ROLLBACK
*/