SELECT 
	ABANCOHORFUNDETALHE.CODCOLIGADA, 
	ABANCOHORFUNDETALHE.IDBANCOHORFUNDETALHE, 
	ABANCOHORFUNDETALHE.CHAPA, 
	'DATA' = CONVERT(VARCHAR, ABANCOHORFUNDETALHE.DATA, 103),
	ABANCOHORFUNDETALHE.CODEVENTOPONTO, 
	ABANCOHORFUNDETALHE.CODEVENTO, 
	AEVECALC.DESCRICAO CODEVENTOPONTODESC, 
	AEVECALC.TIPOEVENTO, 
	'' TIPOEVENTODESC,
	'INICIOPERMES' = CONVERT(VARCHAR, ABANCOHORFUNDETALHE.INICIOPERMES, 103),
	'FIMPERMES' = CONVERT(VARCHAR, ABANCOHORFUNDETALHE.FIMPERMES, 103), 
	'INICIOPERMESALTERADO' = CONVERT(VARCHAR, ABANCOHORFUNDETALHE.INICIOPERMESALTERADO, 103), 
	'FIMPERMESALTERADO' = CONVERT(VARCHAR, ABANCOHORFUNDETALHE.FIMPERMESALTERADO, 103),
	ABANCOHORFUNDETALHE.VALOR, 
	ABANCOHORFUNDETALHE.VALORCOMPENSADO, 
	ABANCOHORFUNDETALHE.VALORLANCADO, 
	ABANCOHORFUNDETALHE.TIPOPROCESSO, 
	ABANCOHORFUNDETALHE.TIPOBANCO,
	ABANCOHORFUNDETALHE.CALCULADOPORFORMULA
FROM 
	ABANCOHORFUNDETALHE(NOLOCK), AEVECALC(NOLOCK)
WHERE 
	ABANCOHORFUNDETALHE.CODCOLIGADA = AEVECALC.CODCOLIGADA 
	AND ABANCOHORFUNDETALHE.CODEVENTO = AEVECALC.CODEVENTO 
	AND (	ABANCOHORFUNDETALHE.CODCOLIGADA = 2 
		AND ABANCOHORFUNDETALHE.CHAPA = '000295'
		) 