SELECT 
	AJORNADACALCULADA.CODCOLIGADA, 
	AJORNADACALCULADA.CHAPA, 
	CONVERT(VARCHAR, AJORNADACALCULADA.DATAREFERENCIA, 103) AS 'DATAREFERENCIA', 
	AJORNADACALCULADA.IDJORNADA, 
	AJORNADACALCULADA.OCORRENCIACRITICADA, 
	AJORNADACALCULADA.CODUSUARIOOCORRENCIACRITICADA, 
	AJORNADACALCULADA.REFERENCIABATIDAALTERADA, 
	SUM(AAVISOCALCULADO.VALIDADO) VALIDADO,
	COUNT (AAVISOCALCULADO.CODAVISO) AVISO
FROM 
	AJORNADACALCULADA(NOLOCK) LEFT OUTER JOIN AAVISOCALCULADO(NOLOCK)
	ON AJORNADACALCULADA.CODCOLIGADA = AAVISOCALCULADO.CODCOLIGADA
	AND AJORNADACALCULADA.CHAPA      = AAVISOCALCULADO.CHAPA
	AND AJORNADACALCULADA.DATAREFERENCIA = AAVISOCALCULADO.DATAREFERENCIA
	AND AJORNADACALCULADA.IDJORNADA = AAVISOCALCULADO.IDJORNADA 
WHERE 
	(AJORNADACALCULADA.CODCOLIGADA = 1 AND 
	AJORNADACALCULADA.CHAPA = '005755' AND 
	AJORNADACALCULADA.DATAREFERENCIA >= '2024-03-01' AND 
	AJORNADACALCULADA.DATAREFERENCIA <= '2024-03-30'
	) 
GROUP BY 
	AJORNADACALCULADA.CODCOLIGADA, AJORNADACALCULADA.CHAPA, 
	AJORNADACALCULADA.DATAREFERENCIA, AJORNADACALCULADA.IDJORNADA,
	AJORNADACALCULADA.OCORRENCIACRITICADA, AJORNADACALCULADA.CODUSUARIOOCORRENCIACRITICADA, AJORNADACALCULADA.REFERENCIABATIDAALTERADA