SELECT  
	AMOVFUNDIA.CODCOLIGADA,
	AMOVFUNDIA.CHAPA,
	'DATA'	=	CONVERT(VARCHAR,AMOVFUNDIA.DATA, 103),
	AMOVFUNDIA.CODEVE,
	AMOVFUNDIA.NUMHORAS,
	AMOVFUNDIA.VALOR,
	PEVENTO.DESCRICAO
FROM  
	AMOVFUNDIA(NOLOCK), PEVENTO (NOLOCK)
WHERE 
		AMOVFUNDIA.CODCOLIGADA = PEVENTO.CODCOLIGADA
	AND	AMOVFUNDIA.CODEVE = PEVENTO.CODIGO
	AND (		AMOVFUNDIA.CODCOLIGADA = 1 
			AND AMOVFUNDIA.CHAPA = '005755' 
			AND AMOVFUNDIA.DATA >= '2024-03-01'
			AND AMOVFUNDIA.DATA <= '2024-03-30'
		)