SELECT  
	AMOVFUN.CODCOLIGADA,
	AMOVFUN.CHAPA,
	AMOVFUN.INICIOPER,
	AMOVFUN.FIMPER,
	AMOVFUN.CODEVE,
	AMOVFUN.ANOCOMP,
	AMOVFUN.MESCOMP,
	AMOVFUN.NUMHORAS,
	AMOVFUN.VALOR,
	AMOVFUN.IDMOVTEMP,
	AMOVFUN.CODCCUSTO, 
	AMOVFUN.IDITEMCONTABIL,
	AMOVFUN.IDCLASSEVALOR,
	PEVENTO.DESCRICAO EVENTO,
	PEVENTO.VALHORDIAREF,
	'' CONSIDERADOPARALANCAMENTOIMG,
	(SELECT 1
	FROM   AEVELAN (NOLOCK) 
	WHERE  AMOVFUN.CODCOLIGADA = AEVELAN.CODCOLIGADA 
	AND    AEVELAN.CODPARCOL = APARFUN.CODPARCOL
	AND    AMOVFUN.CODEVE = AEVELAN.CODEVELAN) 
	AS 'CONSIDERADOPARALANCAMENTO'
FROM   
	AMOVFUN(NOLOCK), 
	PEVENTO(NOLOCK), 
	APARFUN(NOLOCK)
WHERE  
		   AMOVFUN.CODCOLIGADA = PEVENTO.CODCOLIGADA
	AND    AMOVFUN.CODEVE = PEVENTO.CODIGO
	AND    AMOVFUN.CODCOLIGADA = APARFUN.CODCOLIGADA
	AND    AMOVFUN.CHAPA = APARFUN.CHAPA
	AND (		AMOVFUN.CODCOLIGADA = 1
			AND AMOVFUN.CHAPA = '000124'
			AND AMOVFUN.INICIOPER >= '2024-03-01'
			AND AMOVFUN.FIMPER <= '2024-04-30'
		) 