SELECT 
	AOCORRENCIACALCULADA.CODCOLIGADA, 
	AOCORRENCIACALCULADA.CHAPA, 
	CONVERT(VARCHAR, AOCORRENCIACALCULADA.DATAREFERENCIA, 103)	AS 'DATA', 
	CONVERT(VARCHAR, AOCORRENCIACALCULADA.INICIO, 103)			AS 'INICIO',
	CONVERT(VARCHAR, AOCORRENCIACALCULADA.FIM, 103)				AS 'FIM',
	AOCORRENCIACALCULADA.TIPOOCORRENCIA,
	ATIPOOCORRENCIA.DESCRICAO,
	AOCORRENCIACALCULADA.ATITUDE,
	CONVERT(VARCHAR, AOCORRENCIACALCULADA.DATAREFERENCIA, 103)	AS 'DATAREFERENCIA' 
FROM 
				AOCORRENCIACALCULADA	(NOLOCK)
	INNER JOIN	ATIPOOCORRENCIA			(NOLOCK) ON AOCORRENCIACALCULADA.TIPOOCORRENCIA = ATIPOOCORRENCIA.TIPOOCORRENCIA
WHERE 
		1=1
	AND	AOCORRENCIACALCULADA.CODCOLIGADA = 1
	AND AOCORRENCIACALCULADA.CHAPA = '005638'
	AND AOCORRENCIACALCULADA.DATAREFERENCIA BETWEEN '2024-03-16' AND '2024-04-15'
	AND AOCORRENCIACALCULADA.TIPOOCORRENCIA IN ('EA', 'EDA')
--	AND AOCORRENCIACALCULADA.ATITUDE = 1