SELECT 
	ASALDOBANCOHORFUNDETALHE.CODCOLIGADA, ASALDOBANCOHORFUNDETALHE.CHAPA, ASALDOBANCOHORFUNDETALHE.INICIOPERMES, ASALDOBANCOHORFUNDETALHE.FIMPERMES,
	ASALDOBANCOHORFUNDETALHE.CODEVENTOPONTO, ASALDOBANCOHORFUNDETALHE.CODEVENTO, AEVECALC.DESCRICAO CODEVENTOPONTODESC, AEVECALC.TIPOEVENTO, 
	'' TIPOEVENTODESC, ASALDOBANCOHORFUNDETALHE.VALORPERIODO, ASALDOBANCOHORFUNDETALHE.VALORATUAL, ASALDOBANCOHORFUNDETALHE.VALORLANCADO, 
	ASALDOBANCOHORFUNDETALHE.VALORCOMPENSADO, ASALDOBANCOHORFUNDETALHE.PERCENTUALINCIDENCIA
FROM 
	ASALDOBANCOHORFUNDETALHE(NOLOCK), AEVECALC(NOLOCK)
WHERE  
	ASALDOBANCOHORFUNDETALHE.CODCOLIGADA = AEVECALC.CODCOLIGADA AND
	ASALDOBANCOHORFUNDETALHE.CODEVENTO = AEVECALC.CODEVENTO 
	AND (		ASALDOBANCOHORFUNDETALHE.CODCOLIGADA = 2
			AND ASALDOBANCOHORFUNDETALHE.CHAPA = '000295' 
		)