SELECT 
ASALDOBANCOHOR.CODCOLIGADA, ASALDOBANCOHOR.CHAPA, ASALDOBANCOHOR.INICIOPER,
ASALDOBANCOHOR.FIMPER, ASALDOBANCOHOR.EXTRAANT, ASALDOBANCOHOR.ATRASOANT, 
ASALDOBANCOHOR.FALTAANT, ASALDOBANCOHOR.EXTRAATU, ASALDOBANCOHOR.ATRASOATU, ASALDOBANCOHOR.FALTAATU,((ASALDOBANCOHOR.EXTRAATU + ASALDOBANCOHOR.EXTRAANT) -
(ASALDOBANCOHOR.ATRASOATU + ASALDOBANCOHOR.ATRASOANT +
ASALDOBANCOHOR.FALTAATU + ASALDOBANCOHOR.FALTAANT)) SALDOATUAL
FROM 
ASALDOBANCOHOR(NOLOCK), PFUNC(NOLOCK)
WHERE 
	ASALDOBANCOHOR.CODCOLIGADA = PFUNC.CODCOLIGADA
	AND ASALDOBANCOHOR.CHAPA = PFUNC.CHAPA 
	AND (		ASALDOBANCOHOR.CODCOLIGADA = 2
			AND ASALDOBANCOHOR.CHAPA = '000295'
		) 