DECLARE @ANOINICIAL AS VARCHAR(4)
DECLARE @ANOFINAL AS VARCHAR(4)
DECLARE @MESINICIAL AS VARCHAR(2)
DECLARE @MESFINAL AS VARCHAR(2)
DECLARE @COLIGADA AS SMALLINT;

SET @ANOINICIAL = '2024'
SET @ANOFINAL = '2024'
SET @MESINICIAL = '01'
SET @MESFINAL = '05'
SET @COLIGADA = 1


SELECT TAB.CODCOLIGADA,
       TAB.ANO,
       TAB.MES,
       TAB.CODCCUSTO                                             AS 'COD. CCUSTO',
	   TAB.CODNATUREZA											 AS 'COD. NATUREZA',
	   TAB.IDORCAMENTO,
		TAB.IDPERIODO,
		TAB.IDITMPERIODO,
       SUM(TAB.EXCEDENTE)                                        AS 'EXCEDENTE',
	   CASE WHEN	SUM(TAB.VALORORCADO) + SUM(TAB.RECEBIDO) 
					< 
					SUM(TAB.REALIZADO) + SUM(TAB.EMPENHADO) + SUM(TAB.COMPROMETIDO) + SUM(TAB.CEDIDO)
			
			THEN	( (SUM(TAB.REALIZADO) + SUM(TAB.EMPENHADO) + SUM(TAB.COMPROMETIDO))  - SUM(TAB.VALORORCADO) + SUM(TAB.CEDIDO) - SUM(TAB.RECEBIDO) )
			
			WHEN	SUM(TAB.VALORORCADO) + SUM(TAB.RECEBIDO)
					>= 
					SUM(TAB.REALIZADO) + SUM(TAB.EMPENHADO) + SUM(TAB.COMPROMETIDO) + SUM(TAB.CEDIDO)
			THEN	0
	   END														 AS	'EXCEDENTE_REGRA'

FROM   
	   (SELECT GCOLIGADA.CODCOLIGADA,
               GCOLIGADA.NOMEFANTASIA                'EMPRESA',
               0                                     AS REF,
               CASE
                 WHEN CHARINDEX('-', GCCUSTO.NOME) >= 1 THEN LEFT(GCCUSTO.NOME, CHARINDEX('-', GCCUSTO.NOME) - 1)
                 ELSE GCCUSTO.NOME
               END                                   AS FILIAL,
               YEAR(TITMPERIODOORCAMENTO.DATAINICIO)  AS 'ANO',
               MONTH(TITMPERIODOORCAMENTO.DATAINICIO) AS 'MES',
               TORCAMENTO.CODCCUSTO                  AS 'CODCCUSTO',
               GCCUSTO.NOME                          AS	'CENTRODECUSTO',
			   TITMORCAMENTO.IDORCAMENTO			 AS 'IDORCAMENTO',
				TITMORCAMENTO.IDPERIODO				 AS	'IDPERIODO',
				TITMORCAMENTO.IDITMPERIODO			 AS	'IDITMPERIODO',
               TTBORCAMENTO.CODTBORCAMENTO           AS	'CODNATUREZA',
               TTBORCAMENTO.DESCRICAO                AS	'NATUREZA',
               TITMORCAMENTO.VALORORCADO             AS	'VALORORCADO',
               TITMORCAMENTO.VALORREAL               AS 'REALIZADO',
               TITMORCAMENTO.VALOROPCIONAL2          AS 'COMPROMETIDO',
               TITMORCAMENTO.VALOROPCIONAL1          AS 'EMPENHADO',
               TITMORCAMENTO.VALORRECEBIDO           AS 'RECEBIDO',
               TITMORCAMENTO.VALOREXCEDENTE          AS 'EXCEDENTE',
               TITMORCAMENTO.VALORCEDIDO             AS 'CEDIDO'
        FROM   TORCAMENTO (NOLOCK)
               INNER JOIN GCOLIGADA (NOLOCK)
                       ON TORCAMENTO.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
               INNER JOIN GCCUSTO (NOLOCK)
                       ON TORCAMENTO.CODCOLIGADA = GCCUSTO.CODCOLIGADA
                          AND TORCAMENTO.CODCCUSTO = GCCUSTO.CODCCUSTO
                          AND LEN(GCCUSTO.CODCCUSTO) >= 18
               INNER JOIN TTBORCAMENTO (NOLOCK)
                       ON TORCAMENTO.CODCOLTBORCAMENTO = TTBORCAMENTO.CODCOLIGADA
                          AND TORCAMENTO.CODTBORCAMENTO = TTBORCAMENTO.CODTBORCAMENTO
               INNER JOIN TITMORCAMENTO (NOLOCK)
                       ON TITMORCAMENTO.CODCOLIGADA = TORCAMENTO.CODCOLIGADA
                          AND TITMORCAMENTO.IDORCAMENTO = TORCAMENTO.IDORCAMENTO
                          AND TITMORCAMENTO.IDPERIODO = TORCAMENTO.IDPERIODO
               INNER JOIN TITMPERIODOORCAMENTO (NOLOCK)
                       ON TITMORCAMENTO.CODCOLIGADA = TITMPERIODOORCAMENTO.CODCOLIGADA
                          AND TITMORCAMENTO.IDPERIODO = TITMPERIODOORCAMENTO.IDPERIODO
                          AND TITMORCAMENTO.IDITMPERIODO = TITMPERIODOORCAMENTO.IDITMPERIODO
               INNER JOIN TPERIODOORCAMENTO (NOLOCK)
                       ON TITMPERIODOORCAMENTO.CODCOLIGADA = TPERIODOORCAMENTO.CODCOLIGADA
                          AND TITMPERIODOORCAMENTO.IDPERIODO = TPERIODOORCAMENTO.IDPERIODO
        WHERE  1 = 1
               AND ( TITMORCAMENTO.VALORORCADO > 0
                      OR TITMORCAMENTO.VALOROPCIONAL1 > 0 )
               AND CONVERT(VARCHAR(6), TITMPERIODOORCAMENTO.DATAINICIO, 112) BETWEEN @ANOINICIAL + @MESINICIAL AND @ANOFINAL + @MESFINAL
			   AND GCOLIGADA.CODCOLIGADA = @COLIGADA
			   AND TTBORCAMENTO.CODTBORCAMENTO IN ('2.1.01.001', '2.1.01.002', '2.1.01.003', '2.1.01.004', '2.1.01.005', '2.1.01.006', 
													'2.1.01.007', '2.1.01.008', '2.1.01.009', '2.1.01.010', '2.1.01.011', '2.1.01.012', 
													'2.1.01.013', '2.1.01.014', '2.1.01.015', '2.1.01.016', '2.1.01.017', '2.1.01.018', 
													'2.1.01.019', '2.1.01.020', '2.1.01.021', '2.1.01.022')
        GROUP  BY GCOLIGADA.CODCOLIGADA,
                  GCOLIGADA.NOMEFANTASIA,
                  TITMPERIODOORCAMENTO.DATAINICIO,
                  CASE
                    WHEN CHARINDEX('-', GCCUSTO.NOME) >= 1 THEN LEFT(GCCUSTO.NOME, CHARINDEX('-', GCCUSTO.NOME) - 1)
                    ELSE GCCUSTO.NOME
                  END,
                  YEAR(TITMPERIODOORCAMENTO.DATAINICIO),
                  MONTH(TITMPERIODOORCAMENTO.DATAINICIO),
                  TORCAMENTO.CODCCUSTO,
                  GCCUSTO.NOME,
                  TTBORCAMENTO.CODTBORCAMENTO,
                  TTBORCAMENTO.DESCRICAO,
                  TITMORCAMENTO.VALORORCADO,
                  TITMORCAMENTO.VALOROPCIONAL1,
                  TITMORCAMENTO.VALORRECEBIDO,
                  TITMORCAMENTO.VALOREXCEDENTE,
                  TITMORCAMENTO.VALORCEDIDO,
				  TITMORCAMENTO.VALOROPCIONAL2,
				  TITMORCAMENTO.VALORREAL,
				  TITMORCAMENTO.IDORCAMENTO,
				  TITMORCAMENTO.IDPERIODO,
				  TITMORCAMENTO.IDITMPERIODO
                  ) AS TAB


GROUP  BY 
          TAB.CODCOLIGADA,
          TAB.ANO,
          TAB.MES,
          TAB.CODCCUSTO,
          TAB.CODNATUREZA,
		  TAB.IDORCAMENTO,
		  TAB.IDPERIODO,
		  TAB.IDITMPERIODO
ORDER BY 
	TAB.CODCCUSTO,
	TAB.CODNATUREZA,
	TAB.IDITMPERIODO