DECLARE @ANO_ AS INTEGER;
DECLARE @MES_ AS SMALLINT;
DECLARE @CODCOLIGADA_ AS SMALLINT;

SET @ANO_ = 2024;
SET @MES_ = 2;
SET @CODCOLIGADA_ = 1;

WITH VW_ORCAMENTO AS (
SELECT
		TMOV.CODCOLIGADA									AS	'COD_COLIGADA',
		CASE
        	WHEN CHARINDEX('-', GCCUSTO.NOME) >= 1 
        	THEN LEFT(GCCUSTO.NOME, CHARINDEX('-', GCCUSTO.NOME) - 1)
            ELSE GCCUSTO.NOME
        END															AS	'FILIAL',
		TMOV.CODTMV													AS	'TIPO_MOV',
		TMOV.IDMOV													AS	'ID_MOV',
		SUM(TITMMOV.PRECOUNITARIO)									AS	'PRECOUNITARIO',
		SUM(TITMMOV.PRECOUNITARIOSELEC)								AS	'PRECOUNITARIOSELEC',
		SUM(TITMMOV.VALORUNITARIO)									AS	'VALORUNITARIO',
		SUM(TITMMOV.VALORLIQUIDO)									AS	'VALORLIQUIDO',
		SUM(TITMMOV.RATEIOCCUSTODEPTO)								AS	'RATEIOCCUSTODEPTO',
		SUM(TITMMOV.VALORBRUTOITEMORIG)								AS	'VALORBRUTOITEMORIG',
		TITMMOV.CODCCUSTO											AS	'COD_CC',
		GCCUSTO.NOME												AS	'CENTRO_CUSTO',		
		TITMMOV.CODTBORCAMENTO										AS	'COD_NATUREZA',
		TTBORCAMENTO.DESCRICAO										AS	'NATUREZA_ORCAMENTARIA'
		
	FROM
		TMOV 
			JOIN TITMMOV (NOLOCK)
				ON TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA
					AND TITMMOV.IDMOV = TMOV.IDMOV
			JOIN GCCUSTO (NOLOCK)
				ON GCCUSTO.CODCOLIGADA = TITMMOV.CODCOLIGADA
					AND GCCUSTO.CODCCUSTO = TITMMOV.CODCCUSTO
			JOIN TTBORCAMENTO (NOLOCK)
				ON TTBORCAMENTO.CODTBORCAMENTO = TITMMOV.CODTBORCAMENTO
			
			
	WHERE
		TMOV.CODCOLIGADA = @CODCOLIGADA_
--		AND TMOV.IDPERIODO = CASE	WHEN TMOVORCAMENTO.CODCOLIGADA = 1 THEN 24
--											WHEN TMOVORCAMENTO.CODCOLIGADA = 2 THEN 28
--									  END
--		AND	TMOV.IDITMPERIODO = @MES_
--		AND TMOV.IDMOV IS NOT NULL
--		AND TMOV.TIPO = 'I'
		AND TMOV.CODCOLIGADA	= @CODCOLIGADA_
		AND	YEAR(TMOV.DATAEMISSAO)	= @ANO_			
		AND	MONTH(TMOV.DATAEMISSAO)	= @MES_	
		GROUP BY 
			TMOV.CODCOLIGADA,
			TMOV.IDMOV,
			TITMMOV.CODCCUSTO,
			TMOV.CODTMV,
			TITMMOV.CODTBORCAMENTO,
			GCCUSTO.NOME,
			TTBORCAMENTO.DESCRICAO

)
SELECT DISTINCT
	
	VW_ORCAMENTO.*
	
FROM
	VW_ORCAMENTO


WHERE VW_ORCAMENTO.TIPO_MOV IN ('1.2.01', '1.2.02', '1.2.10', '1.2.18', '1.2.7')

ORDER BY VW_ORCAMENTO.ID_MOV
	