DECLARE @ANOINICIAL AS VARCHAR(4)
DECLARE @ANOFINAL AS VARCHAR(4)
DECLARE @MESINICIAL AS VARCHAR(2)
DECLARE @MESFINAL AS VARCHAR(2)

SET @ANOINICIAL = '2024'
SET @ANOFINAL = '2024'
SET @MESINICIAL = '01'
SET @MESFINAL = '04'

SELECT 
	GCOLIGADA.CODCOLIGADA		AS 'COD_COLIGADA',
	CASE 
		WHEN GCOLIGADA.CODCOLIGADA = 1 THEN 24
		WHEN GCOLIGADA.CODCOLIGADA = 2 THEN 28
	END							AS 'ID_PERIODO',
    YEAR(FLANBAIXA.DATABAIXA)   AS 'ANO',
    MONTH(FLANBAIXA.DATABAIXA)  AS 'MES',
    GCCUSTO.CODCCUSTO           AS 'COD_CC',
	TTBORCAMENTO.CODTBORCAMENTO	AS 'COD_NATUREZA',
    SUM(FLANBAIXARATCCU.VALOR)  AS 'REALIZADO'

FROM  
			 FLAN (NOLOCK)
        JOIN GCOLIGADA (NOLOCK) ON FLAN.CODCOLIGADA = GCOLIGADA.CODCOLIGADA
        JOIN FLANBAIXA (NOLOCK) ON FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA
										AND FLAN.IDLAN = FLANBAIXA.IDLAN
        JOIN FLANBAIXARATCCU (NOLOCK) ON FLANBAIXA.CODCOLIGADA = FLANBAIXARATCCU.CODCOLIGADA
										AND FLANBAIXA.IDBAIXA = FLANBAIXARATCCU.IDBAIXA
        JOIN GCCUSTO (NOLOCK) ON FLANBAIXARATCCU.CODCOLIGADA = GCCUSTO.CODCOLIGADA
										AND FLANBAIXARATCCU.CODCCUSTO = GCCUSTO.CODCCUSTO
										AND LEN(GCCUSTO.CODCCUSTO) >= 18
        JOIN TTBORCAMENTO (NOLOCK) ON FLANBAIXARATCCU.CODCOLNATFINANCEIRA = TTBORCAMENTO.CODCOLIGADA
										AND FLANBAIXARATCCU.CODNATFINANCEIRA = TTBORCAMENTO.CODTBORCAMENTO
WHERE	1 = 1
	AND CONVERT(VARCHAR(6), FLANBAIXA.DATABAIXA, 112) BETWEEN @ANOINICIAL + @MESINICIAL AND @ANOFINAL + @MESFINAL
	AND TTBORCAMENTO.CODTBORCAMENTO IN ('2.1.01.001', '2.1.01.002', '2.1.01.003', '2.1.01.004', '2.1.01.005', '2.1.01.006', 
										'2.1.01.007', '2.1.01.008', '2.1.01.009', '2.1.01.010', '2.1.01.011', '2.1.01.012', 
										'2.1.01.013', '2.1.01.014', '2.1.01.015', '2.1.01.016', '2.1.01.017', '2.1.01.018', 
										'2.1.01.019', '2.1.01.020', '2.1.01.021', '2.1.01.022')

GROUP BY
	GCOLIGADA.CODCOLIGADA,
	FLANBAIXA.DATABAIXA,
	GCCUSTO.CODCCUSTO,
	TTBORCAMENTO.CODTBORCAMENTO
ORDER BY 
	GCOLIGADA.CODCOLIGADA