SELECT 
    ABATFUN.CODCOLIGADA,
    ABATFUN.CHAPA,
    CONVERT(VARCHAR, ABATFUN.[DATA], 103) AS 'DATA',
    CONCAT(
        CASE
            WHEN FLOOR(ABATFUN.BATIDA / 60) < 10 THEN CONCAT('0', FLOOR(ABATFUN.BATIDA / 60)) 
            ELSE CAST(FLOOR(ABATFUN.BATIDA / 60) AS VARCHAR) 
        END, -- Horas
        ':', 
        CASE 
            WHEN ABATFUN.BATIDA % 60 < 10 THEN CONCAT('0', ABATFUN.BATIDA % 60) 
            ELSE CAST(ABATFUN.BATIDA % 60 AS VARCHAR) 
        END -- Minutos
    ) AS 'BATIDA',
    ABATFUN.BATIDA AS 'BATIDA_MINUTOS',
    CASE
        WHEN ABATFUN.STATUS = 'D' THEN 'DIGITADO'
        ELSE ABATFUN.STATUS
    END AS 'STATUS',
    ABATFUN.NATUREZA,
    ABATFUN.CODIGOTERMCOL,
    CONVERT(VARCHAR, ABATFUN.DATAAPROV, 103) AS 'DATAAPROV',
    '' AS DCHORA,
    ABATFUN.IDJORNADA,
    CONVERT(VARCHAR, ABATFUN.DATAREFERENCIA, 103) AS 'DATAREFERENCIA',
    CONVERT(VARCHAR, ABATFUN.DATAINSERCAO, 103) AS 'DATAINSERCAO',
    ABATFUN.IDAAFDT,
    ABATFUN.NATUREZAALTERADA,
    ABATFUN.IDAPORTARIA373
FROM   
    ABATFUN (NOLOCK)
LEFT JOIN
    APORTARIA373 (NOLOCK) ON  APORTARIA373.CODCOLIGADA = ABATFUN.CODCOLIGADA
                            AND APORTARIA373.CHAPA = ABATFUN.CHAPA
                            AND APORTARIA373.ID = ABATFUN.IDAPORTARIA373
WHERE  
			1 = 1
	AND		ABATFUN.STATUS = 'D'
	AND (ABATFUN.CODCOLIGADA = 2
	--AND (ABATFUN.CHAPA = :CHAPA OR :CHAPA = 0)
	AND (ABATFUN.DATAREFERENCIA BETWEEN '2024-02-19' AND '2024-02-19' OR ABATFUN.DATA BETWEEN '2024-02-19' AND '2024-02-19')
	AND (APORTARIA373.DESCONSIDERADA = 0 OR APORTARIA373.DESCONSIDERADA IS NULL))
ORDER  BY 
	ABATFUN.DATA,
    ABATFUN.BATIDA 