SELECT 
	CODCOLIGADA, CHAPA, DATA, INICIO, FIM, TIPOOCORRENCIA, ATITUDE,  NUMHORAS
FROM 
	AJUSTFUN (NOLOCK)
WHERE 
		AJUSTFUN.CODCOLIGADA = 2
	AND AJUSTFUN.CHAPA = '000295' 
	AND AJUSTFUN.DATA BETWEEN '2024-03-01' AND '2024-03-30'
	AND AJUSTFUN.TIPOOCORRENCIA IN ('E', 'C', 'D', 'R')
	AND AJUSTFUN.ATITUDE = 1
