SELECT 
	PFUNC.CODCOLIGADA, PFUNC.CHAPA, PFUNC.NOME, PFUNC.DATADEMISSAO, PFUNC.DATAADMISSAO,
	PFUNC.RESCISAOCALCULADA, PFUNC.CODSITUACAO, PFUNC.CODGRPQUIOSQUE, PFUNC.DTTRANSFERENCIA
FROM 
	PFUNC(NOLOCK)
WHERE 
	(CODCOLIGADA = 2 AND CHAPA = '000295') /*AND*/ 