SELECT 
	TITMORCAMENTO.CODCOLIGADA,
	TMOV.CODCCUSTO,
	TITMMOV.CODTBORCAMENTO,
	TMOV.CODTMV,
	TITMORCAMENTO.IDORCAMENTO,
	TMOVORCAMENTO.IDMOVORCAMENTO,
	TMOVORCAMENTO.IDMOV,
	TITMORCAMENTO.IDPERIODO,
	TITMORCAMENTO.IDITMPERIODO,
	TMOVORCAMENTO.VALOREXCEDENTE AS 'EXCEDENTE TMOVORCAMENTO',
	TITMORCAMENTO.VALOREXCEDENTE AS 'EXCEDENTE TITMORCAMENTO'

FROM 
			TMOVORCAMENTO	(NOLOCK)
	JOIN	TMOV			(NOLOCK) ON TMOVORCAMENTO.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVORCAMENTO.IDMOV = TMOV.IDMOV
	JOIN	TITMMOV			(NOLOCK) ON TITMMOV.CODCOLIGADA = TMOV.CODCOLIGADA AND TITMMOV.IDMOV = TMOV.IDMOV
	JOIN	TITMORCAMENTO	(NOLOCK) ON TMOVORCAMENTO.CODCOLIGADA = TITMORCAMENTO.CODCOLIGADA AND TMOVORCAMENTO.IDORCAMENTO = TITMORCAMENTO.IDORCAMENTO AND TMOVORCAMENTO.IDITMPERIODO = TITMORCAMENTO.IDITMPERIODO

WHERE
		1=1
	AND TITMORCAMENTO.IDPERIODO IN (24, 28)
	AND (TMOVORCAMENTO.VALOREXCEDENTE  < 0 OR TITMORCAMENTO.VALOREXCEDENTE  < 0)

ORDER BY
	TITMORCAMENTO.CODCOLIGADA,
	TITMORCAMENTO.IDORCAMENTO,
	TMOVORCAMENTO.IDMOVORCAMENTO

SELECT CODCOLIGADA, IDORCAMENTO, IDPERIODO, IDITMPERIODO, VALOREXCEDENTE FROM TITMORCAMENTO WHERE IDORCAMENTO = 315152 AND IDPERIODO = 24 AND IDITMPERIODO = 4 AND VALOREXCEDENTE = -136.0401;


/*
BEGIN TRANSACTION
	UPDATE TITMORCAMENTO SET VALOREXCEDENTE = 0 WHERE IDORCAMENTO = 315152 AND IDPERIODO = 24 AND IDITMPERIODO = 4 AND VALOREXCEDENTE = -136.0401
ROLLBACK
*/
