SELECT 
	OBJECT_NAME(PARENT_ID)										AS 'TABELA', 
	NAME														AS 'NOME_TRIGGER',
	CASE IS_DISABLED WHEN 1 THEN 'INATIVO' ELSE 'ATIVO' END		AS 'STATUS'
FROM 
	SYS.TRIGGERS
WHERE 
		1=1
	AND IS_DISABLED = 0  /* TRIGGER ATIVAS = 0 INATIVAS = 1	*/
--	AND OBJECT_NAME(PARENT_ID) LIKE 'PFUNC%' /*	BUSCA TABELA	*/
ORDER BY 
	TABELA;