WITH
	VW_MOVIMENTO
	AS
	(
		
		SELECT DISTINCT
			TMOV1.CODCOLIGADA,
			TMOV1.CODTMV,
			TMOV1.DATAEMISSAO,
			MONTH (TMOV1.DATAEMISSAO) AS MES,
			(
				SELECT
				MAX(RASTREIAMOVIMENTOS.IDMOV)
			FROM
				RASTREIAMOVIMENTOS (TMOV.CODCOLIGADA, TMOV.IDMOV)
			) AS IDMOV_RELAC,
			TITMMOV.IDPRD,
			TITMMOV.CODCCUSTO,
			GCCUSTO.NOME AS CENTRO_CUSTO,
			TTBORCAMENTO.DESCRICAO AS NATUREZA_ORCAMENTARIA,
			TITMMOV.CODTBORCAMENTO,
			TITMMOV.QUANTIDADETOTAL,
			TITMMOV.VALORBRUTOITEM,
			TMOV.CODCFO,
			FCFO.NOMEFANTASIA AS FORNECEDOR
		FROM
			TMOV
			JOIN TMOV TMOV1 (NOLOCK) ON TMOV1.CODCOLIGADA = TMOV.CODCOLIGADA
				AND TMOV1.IDMOV = (
				SELECT
					MAX(RASTREIAMOVIMENTOS.IDMOV)
				FROM
					RASTREIAMOVIMENTOS (TMOV.CODCOLIGADA, TMOV.IDMOV)
			)
			JOIN TITMMOV (NOLOCK) ON TITMMOV.CODCOLIGADA = TMOV1.CODCOLIGADA
				AND TITMMOV.IDMOV = TMOV1.IDMOV
			JOIN GCCUSTO (NOLOCK) ON GCCUSTO.CODCOLIGADA = TITMMOV.CODCOLIGADA
				AND GCCUSTO.CODCCUSTO = TITMMOV.CODCCUSTO
			JOIN TTBORCAMENTO (NOLOCK) ON TTBORCAMENTO.CODTBORCAMENTO = TITMMOV.CODTBORCAMENTO
			LEFT JOIN FCFO (NOLOCK) ON FCFO.CODCFO = TMOV.CODCFO
		WHERE
			1 = 1
			AND TMOV.CODCOLIGADA = 2
			AND YEAR (TMOV.DATAEMISSAO) = 2024 -- Condi��o para selecionar registros com data de emiss�o no ano de 2024
			AND MONTH (TMOV.DATAEMISSAO) = 1
		-- Condi��o para selecionar registros com data de emiss�o no ano de 2024
		--	AND	TMOV.IDMOV				= 441493--441546	-- Condi��o para selecionar registros com ID de movimenta��o igual a 560003       454154  FORNECEDOR
		--AND	TMOV.CODTMV				<> '1.1.03'	
	),
	VW_ORCAMENTO
	AS
	(
		SELECT
			TMOVORCAMENTO.CODCOLIGADA,
			TMOVORCAMENTO.IDITMPERIODO,
			TMOVORCAMENTO.IDMOV,
			TMOVORCAMENTO.IDORCAMENTO,
			TMOVORCAMENTO.IDPERIODO,
			TITMORCAMENTO.VALORORCADO,
			TITMORCAMENTO.VALOROPCIONAL2 AS 'COMPROMETIDO',
			TORCAMENTO.CODCCUSTO,
			TORCAMENTO.CODTBORCAMENTO
		FROM
			TMOVORCAMENTO (NOLOCK)
			JOIN TITMORCAMENTO (NOLOCK) ON TITMORCAMENTO.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA
				AND TITMORCAMENTO.IDORCAMENTO = TMOVORCAMENTO.IDORCAMENTO
				AND TITMORCAMENTO.IDITMPERIODO = TMOVORCAMENTO.IDITMPERIODO
				AND TITMORCAMENTO.IDPERIODO = TMOVORCAMENTO.IDPERIODO
			JOIN TORCAMENTO (NOLOCK) ON TORCAMENTO.CODCOLIGADA = TITMORCAMENTO.CODCOLIGADA
				AND TORCAMENTO.IDPERIODO = TITMORCAMENTO.IDPERIODO
				AND TORCAMENTO.IDORCAMENTO = TITMORCAMENTO.IDORCAMENTO
		WHERE
			TMOVORCAMENTO.CODCOLIGADA = 2
			AND TMOVORCAMENTO.IDPERIODO = 28
			AND TMOVORCAMENTO.IDITMPERIODO = 1
			AND TMOVORCAMENTO.IDMOV IS NOT NULL
	)
SELECT DISTINCT
	VW_MOVIMENTO.*,
	VW_ORCAMENTO.VALORORCADO,
	VW_ORCAMENTO.COMPROMETIDO
FROM
	VW_MOVIMENTO
	JOIN VW_ORCAMENTO ON VW_ORCAMENTO.CODCOLIGADA = VW_MOVIMENTO.CODCOLIGADA
		AND VW_ORCAMENTO.IDMOV = VW_MOVIMENTO.IDMOV_RELAC
		AND VW_ORCAMENTO.CODCCUSTO = VW_MOVIMENTO.CODCCUSTO
		AND VW_ORCAMENTO.CODTBORCAMENTO = VW_MOVIMENTO.CODTBORCAMENTO
WHERE
	VW_MOVIMENTO.IDMOV_RELAC = 442776