DECLARE @ANO_ AS INTEGER;
DECLARE @MES_INICIAL_ AS SMALLINT;
DECLARE @MES_FINAL_ AS SMALLINT;
DECLARE @CODCOLIGADA_ AS SMALLINT;
DECLARE	@CODFILIAL_ AS SMALLINT;

SET @ANO_ = 2024
SET @MES_INICIAL_ = 3
SET @MES_FINAL_ = 6
SET @CODCOLIGADA_ = 1
SET @CODFILIAL_ = 6;

WITH VW_ORCAMENTO AS
(
SELECT 

		TMOV.CODCOLIGADA,
		TMOV.CODFILIAL												AS	'CODFILIAL',
		GFILIAL.NOMEFANTASIA										AS	'FILIAL',
		MONTH(TMOV.DATAEMISSAO)									AS	'MES',
		TMOV.IDMOV,
		--TMOV.IDORCAMENTO									AS	'ID_ORCAMENTO',
		--TMOV.IDPERIODO,			
		TITMMOV.CODCCUSTO										AS	'COD_CC',
		GCCUSTO.NOME												AS	'CENTRO_CUSTO',
		TPRODUTODEF.CODTBORCAMENTO									AS	'COD_NATUREZA',
		--TTBORCAMENTO.DESCRICAO										AS	'NATUREZA_ORCAMENTARIA',
		TMOV.CODTMV													AS	'CODTMV',
		CONCAT(TMOV.CODTMV,' - ',TTMV.NOME)							AS	'TIPO_MOV',
		CASE 
        WHEN TITMTMV.EFEITOSALDOORCA = 'T' THEN 'AUMENTA O COMPROMETIDO'
        WHEN TITMTMV.EFEITOSALDOORCA = 'N' THEN 'NENHUM EFEITO NO ORÇAMENTO'
        WHEN TITMTMV.EFEITOSALDOORCA = 'M' THEN 'AUMENTA O EMPENHADO'
        WHEN TITMTMV.EFEITOSALDOORCA = 'D' THEN 'DIMINUI O REALIZADO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'A' THEN 'AUMENTA O REALIZADO' 
		END															AS	'EFEITO',
		TITMMOV.IDPRD												AS	'COD_PRDT',
		TPRD.DESCRICAO												AS	'DESC_PRODUTO',
		COALESCE(FCFO.NOME, 'MOVIMENTO SEM FORNECEDOR')				AS	'FORNCECEDOR',
		AVG(TITMMOV.QUANTIDADETOTAL)								AS	'QTD_PRDT',
		AVG(TITMMOV.PRECOUNITARIO)									AS	'VLR_UND_PRDT',
		AVG(TITMMOV.VALORBRUTOITEM)									AS	'VLR_TOTAL_ITEM'


FROM 
TITMMOV (NOLOCK)
	JOIN TMOV (NOLOCK)
		ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA
			AND TITMMOV.IDMOV = TMOV.IDMOV

LEFT JOIN FCFO (NOLOCK)
				ON FCFO.CODCFO = TMOV.CODCFO
			
			JOIN GCCUSTO (NOLOCK)
				ON GCCUSTO.CODCOLIGADA = TITMMOV.CODCOLIGADA
					AND GCCUSTO.CODCCUSTO = TITMMOV.CODCCUSTO
			JOIN TPRD (NOLOCK)
				ON TPRD.IDPRD = TITMMOV.IDPRD
					AND TPRD.CODCOLIGADA = TITMMOV.CODCOLIGADA 
			JOIN TPRODUTODEF (NOLOCK) 
				ON TPRD.CODCOLIGADA = TPRODUTODEF.CODCOLIGADA 
					AND TPRD.IDPRD = TPRODUTODEF.IDPRD
			JOIN GFILIAL (NOLOCK)
				ON	TMOV.CODCOLIGADA = GFILIAL.CODCOLIGADA
					AND	TMOV.CODFILIAL = GFILIAL.CODFILIAL
			JOIN TTMV	(NOLOCK)
				ON	TMOV.CODCOLIGADA = TTMV.CODCOLIGADA
					AND	TMOV.CODTMV	= TTMV.CODTMV
			JOIN TTMVEXT (NOLOCK) 
				ON TTMV.CODCOLIGADA = TTMVEXT.CODCOLIGADA 
					AND TTMV.CODTMV = TTMVEXT.CODTMV
			JOIN TITMTMV (NOLOCK) 
				ON TITMTMV.CODCOLIGADA = TTMVEXT.CODCOLIGADA 
					AND TITMTMV.CODTMV = TTMVEXT.CODTMV
WHERE 
	TITMMOV.CODTBORCAMENTO = '2.5.01.019' 
	--AND TITMMOV.CODCCUSTO = '01.02.06.01.01.001' 
	AND YEAR(TITMMOV.DATAEMISSAO) = 2024
	AND TMOV.CODFILIAL = 6
GROUP BY 
		TMOV.CODCOLIGADA,
		MONTH(TMOV.DATAEMISSAO),
		TMOV.IDMOV,
		
		TITMMOV.CODCCUSTO,
		TPRODUTODEF.CODTBORCAMENTO,
		TMOV.CODTMV,
		TTMV.NOME,
		TITMMOV.IDPRD,
		TPRD.DESCRICAO,
		FCFO.NOME,
		GCCUSTO.NOME,
		
		TMOV.CODFILIAL,
		GFILIAL.NOMEFANTASIA,
		TITMTMV.EFEITOSALDOORCA
),
VW_RELAC AS (
SELECT DISTINCT
	TMOV.CODCOLIGADA,
	TMOV.IDMOV,
	TMOV.DATAEMISSAO,
	(	SELECT MAX(RASTREIAMOVIMENTOS.IDMOV) 
			FROM RASTREIAMOVIMENTOS(TMOV.CODCOLIGADA,TMOV.IDMOV)) AS 'IDMOV_RELAC'
		
FROM
	TMOV (NOLOCK)
WHERE
		1 						= 1
	AND TMOV.CODCOLIGADA		= @CODCOLIGADA_
	AND	YEAR(TMOV.DATAEMISSAO)	= @ANO_			
	AND	MONTH(TMOV.DATAEMISSAO) BETWEEN @MES_INICIAL_ AND @MES_FINAL_
)
SELECT DISTINCT
	VW_ORCAMENTO.*,
	(	SELECT N2.CODTBORCAMENTO + ' - '
			FROM   TITMMOV AS N2 (NOLOCK)
			WHERE  CODCOLIGADA = N2.CODCOLIGADA
               AND LEFT(VW_ORCAMENTO.COD_NATUREZA, 3) = N2.CODTBORCAMENTO
	)															AS 'GRUPO'
FROM
	VW_ORCAMENTO
		JOIN VW_RELAC
			ON VW_RELAC.CODCOLIGADA = VW_ORCAMENTO.CODCOLIGADA
				AND VW_RELAC.IDMOV_RELAC = VW_ORCAMENTO.IDMOV
WHERE	1=1
	

ORDER BY VW_ORCAMENTO.IDMOV,
		 VW_ORCAMENTO.CODTMV
				