DECLARE @ANOINICIAL AS VARCHAR(4) 
DECLARE @ANOFINAL	AS VARCHAR(4) 
DECLARE @MESINICIAL AS VARCHAR(2)  
DECLARE @MESFINAL	AS VARCHAR(2) 
DECLARE @ANOMES_INICIAL	AS VARCHAR(6)
DECLARE @ANOMES_FINAL	AS VARCHAR(6)

SET @ANOINICIAL = '2024'
SET @ANOFINAL	= '2024'
SET @MESINICIAL = '01'
SET @MESFINAL	= '06'
SET @ANOMES_INICIAL = @ANOINICIAL + @MESINICIAL
SET @ANOMES_FINAL	= @ANOFINAL + @MESFINAL

;  

WITH TAB AS
(SELECT	
		TMOV.CODCOLIGADA,
		GFILIAL.CODFILIAL,
		TMOVLAN.IDMOV					AS IDMOV,
		TMOV.CODTMV,
		FLAN.IDLAN						AS REF,
		YEAR(FLANBAIXA.DATABAIXA)		AS ANO,
		MONTH(FLANBAIXA.DATABAIXA)		AS MES,
		GCCUSTO.CODCCUSTO				AS CODCCUSTO,
		TTBORCAMENTO.CODTBORCAMENTO		AS CODNATUREZA,
		FLANBAIXARATCCU.VALOR			AS REALIZADO,
		0								AS COMPROMETIDO,
		FCFO.CODCFO						AS CODCFO,
		FCFO.NOME						AS FORNECEDOR
FROM	
			   TMOV (NOLOCK)
	INNER JOIN GFILIAL (NOLOCK)
								ON GFILIAL.CODCOLIGADA = TMOV.CODCOLIGADA
								AND GFILIAL.CODFILIAL = TMOV.CODFILIAL
	INNER JOIN TMOVLAN (NOLOCK)
								ON TMOV.CODCOLIGADA = TMOVLAN.CODCOLIGADA
								AND TMOV.IDMOV = TMOVLAN.IDMOV
	INNER JOIN FLAN (NOLOCK)
								ON FLAN.CODCOLIGADA = TMOVLAN.CODCOLIGADA
								AND FLAN.IDLAN = TMOVLAN.IDLAN
	LEFT JOIN  FLANBAIXA (NOLOCK)
								ON	FLAN.CODCOLIGADA	= FLANBAIXA.CODCOLIGADA
								AND FLAN.IDLAN			= FLANBAIXA.IDLAN
	INNER JOIN FLANBAIXARATCCU (NOLOCK) 
								ON	FLANBAIXARATCCU.CODCOLIGADA = FLANBAIXA.CODCOLIGADA
								AND FLANBAIXARATCCU.IDBAIXA		= FLANBAIXA.IDBAIXA
	INNER JOIN TTBORCAMENTO (NOLOCK) 
								ON	TTBORCAMENTO.CODCOLIGADA	= FLANBAIXARATCCU.CODCOLNATFINANCEIRA
								AND TTBORCAMENTO.CODTBORCAMENTO = FLANBAIXARATCCU.CODNATFINANCEIRA 
	INNER JOIN GCCUSTO (NOLOCK) 
								ON	GCCUSTO.CODCOLIGADA = FLANBAIXARATCCU.CODCOLIGADA
								AND GCCUSTO.CODCCUSTO	= FLANBAIXARATCCU.CODCCUSTO
								AND LEN(GCCUSTO.CODCCUSTO) >= 18
	INNER JOIN GCOLIGADA (NOLOCK)
								ON GCOLIGADA.CODCOLIGADA = FLAN.CODCOLIGADA
	INNER JOIN FCFO (NOLOCK)
								ON FCFO.CODCFO			= FLAN.CODCFO		


WHERE	
			CONVERT(VARCHAR(6),FLANBAIXA.DATABAIXA,112) BETWEEN @ANOMES_INICIAL AND @ANOMES_FINAL 
	AND		FLANBAIXA.STATUS = 0
	AND		FLAN.PAGREC = 2
	AND		FLAN.NFOUDUP IN (0,2)
	AND		FLAN.CLASSIFICACAO <> 4
	AND		FLAN.STATUSLAN <> 2 
	AND		FLANBAIXARATCCU.VALOR > 0

GROUP BY	
			GCOLIGADA.CODCOLIGADA,   
			GCOLIGADA.NOMEFANTASIA,
			FLAN.IDLAN,
			CASE
			WHEN CHARINDEX('-', GCCUSTO.NOME) >= 1 THEN LEFT(GCCUSTO.NOME, CHARINDEX('-', GCCUSTO.NOME) - 1)
			ELSE GCCUSTO.NOME
			END,
			YEAR(FLANBAIXA.DATABAIXA),
			MONTH(FLANBAIXA.DATABAIXA),
			GCCUSTO.CODCCUSTO,
			GCCUSTO.NOME,
			TTBORCAMENTO.CODTBORCAMENTO,
			TTBORCAMENTO.DESCRICAO,
			FLAN.DATAEMISSAO,  
			FLANBAIXARATCCU.VALOR,	
			FCFO.CODCFO,
			FCFO.NOME,
			TMOVLAN.IDMOV,
			TMOV.CODTMV,
			TMOV.CODCOLIGADA,
		GFILIAL.CODFILIAL

UNION ALL 

SELECT	
		TMOV.CODCOLIGADA,
		GFILIAL.CODFILIAL,
		TMOVLAN.IDMOV				AS IDMOV,
		TMOV.CODTMV,
		FLAN.IDLAN					AS REF,
		YEAR(FLAN.DATAVENCIMENTO)	AS ANO,
		MONTH(FLAN.DATAVENCIMENTO)	AS MES,
		GCCUSTO.CODCCUSTO			AS CODCCUSTO,
		TTBORCAMENTO.CODTBORCAMENTO AS CODNATUREZA,
		0							AS REALIZADO,
		FLANRATCCU.VALOR			AS COMPROMETIDO,
		FCFO.CODCFO						AS CODCFO,
		FCFO.NOME					AS FORNECEDOR

		
FROM 
				TMOV (NOLOCK)
	INNER JOIN TMOVLAN (NOLOCK)
								ON TMOV.CODCOLIGADA = TMOVLAN.CODCOLIGADA
								AND TMOV.IDMOV = TMOVLAN.IDMOV
	INNER JOIN FLAN (NOLOCK)
								ON FLAN.CODCOLIGADA = TMOVLAN.CODCOLIGADA
								AND FLAN.IDLAN = TMOVLAN.IDLAN
	INNER JOIN GFILIAL (NOLOCK)
										ON GFILIAL.CODCOLIGADA = TMOV.CODCOLIGADA
										AND GFILIAL.CODFILIAL = TMOV.CODFILIAL
	INNER JOIN FCFO (NOLOCK)
										ON FLAN.CODCFO = FCFO.CODCFO
	LEFT JOIN FLANRATCCU (NOLOCK) 
										ON FLANRATCCU.CODCOLIGADA = FLAN.CODCOLIGADA
										AND FLANRATCCU.IDLAN = FLAN.IDLAN
	LEFT JOIN FLANBAIXA (NOLOCK) 
										ON FLAN.CODCOLIGADA = FLANBAIXA.CODCOLIGADA
										AND FLAN.IDLAN = FLANBAIXA.IDLAN
										AND FLANBAIXA.STATUS = 0
	INNER JOIN TTBORCAMENTO (NOLOCK) 
										ON FLANRATCCU.CODCOLNATFINANCEIRA = TTBORCAMENTO.CODCOLIGADA
										AND FLANRATCCU.CODNATFINANCEIRA = TTBORCAMENTO.CODTBORCAMENTO
	INNER JOIN GCCUSTO (NOLOCK)
										ON FLANRATCCU.CODCOLIGADA = GCCUSTO.CODCOLIGADA
										AND FLANRATCCU.CODCCUSTO = GCCUSTO.CODCCUSTO
										AND LEN(GCCUSTO.CODCCUSTO) >= 18
	INNER JOIN GCOLIGADA (NOLOCK) 
										ON FLAN.CODCOLIGADA = GCOLIGADA.CODCOLIGADA

WHERE		
			FLAN.PAGREC = 2
	AND		FLAN.NFOUDUP IN (0,2)
	AND		FLAN.CLASSIFICACAO <> 4
	AND		FLAN.STATUSLAN <> 2
	AND		CONVERT(VARCHAR(6),FLAN.DATAVENCIMENTO,112) BETWEEN @ANOMES_INICIAL AND @ANOMES_FINAL
	AND		FLANBAIXA.DATABAIXA IS NULL


GROUP BY
	TMOVLAN.IDMOV,
	TMOV.CODTMV,
	GCOLIGADA.CODCOLIGADA,
	GCOLIGADA.NOMEFANTASIA,
	FLAN.IDLAN,
	FLAN.CODFILIAL,		
	TTBORCAMENTO.CODTBORCAMENTO,
	TTBORCAMENTO.DESCRICAO,
	FLAN.DATAVENCIMENTO,
	GCCUSTO.CODCCUSTO,
	GCCUSTO.NOME,
	FLANBAIXA.DATABAIXA,	
	FLAN.DATAEMISSAO,		
	FLANRATCCU.VALOR,
	FCFO.CODCFO,
	FCFO.NOME,
	TMOV.CODCOLIGADA,
		GFILIAL.CODFILIAL

),
GERAL AS
(SELECT	
		TAB.CODCOLIGADA,
		TAB.CODFILIAL,
		TAB.ANO,
		TAB.MES,
		TAB.IDMOV,
		TAB.CODTMV,
		TAB.REF,
		TAB.CODNATUREZA,  
		TAB.CODCCUSTO					  AS COD_CCUSTO,
		TAB.CODCFO						AS CODCFO,
		TAB.FORNECEDOR				AS FORNECEDOR,
		SUM(TAB.REALIZADO)			AS VALOR_REALIZADO,
		SUM(TAB.COMPROMETIDO)		AS COMPROMETIDO
		
FROM TAB

GROUP BY	
			TAB.ANO,
			TAB.MES,
			TAB.IDMOV,
			TAB.CODTMV,
			TAB.REF,
			TAB.CODCCUSTO,
			TAB.CODNATUREZA,
			TAB.CODCFO,
			TAB.FORNECEDOR,
			TAB.CODCOLIGADA,
		TAB.CODFILIAL
			
HAVING	
		SUM(REALIZADO)		> 0	OR 
		SUM(COMPROMETIDO)	> 0
)


SELECT	
		GERAL.CODCOLIGADA,
		GERAL.CODFILIAL,
		GERAL.ANO,
		GERAL.MES,
		GERAL.IDMOV,
		GERAL.CODTMV,
		GERAL.REF,		
		GERAL.CODNATUREZA,
		GERAL.COD_CCUSTO  AS 'COD. CCUSTO',
		GERAL.VALOR_REALIZADO,
		GERAL.COMPROMETIDO, 
		GERAL.CODCFO,
		GERAL.FORNECEDOR
		
FROM GERAL

ORDER BY
	GERAL.CODCOLIGADA ASC,
	GERAL.CODFILIAL  ASC,
	GERAL.ANO DESC,
	GERAL.MES ASC

