SELECT 
	TMOV.CODCOLIGADA,
	CONVERT(VARCHAR,TMOV.DATAEMISSAO,103) AS DATAEMISSAO,
	TITMMOV.CODTBORCAMENTO	AS COD_NATUREZA,
	TMOV.CODTMV,
	(SELECT DISTINCT MAX(RASTREIAMOVIMENTOS.IDMOV) FROM RASTREIAMOVIMENTOS (TMOV.CODCOLIGADA, TMOV.IDMOV))	AS IDMOV,
	TMOVORCAMENTO.IDORCAMENTO,
	TMOV.VALORBRUTO AS REALIZADO
--	TMOV.VALORBRUTOINTERNO AS COMPROMETIDO
FROM
		 TMOV		(NOLOCK)
	
	JOIN TITMMOV (NOLOCK) 
									ON TMOV.CODCOLIGADA = TITMMOV.CODCOLIGADA
									AND TMOV.IDMOV = TITMMOV.IDMOV
	JOIN TMOVORCAMENTO (NOLOCK)
									ON TMOV.CODCOLIGADA = TMOVORCAMENTO.CODCOLIGADA
									AND TMOV.IDMOV = TMOVORCAMENTO.IDMOV
WHERE
		1=1
	AND MONTH(TMOV.DATAEMISSAO) = 4
	AND YEAR(TMOV.DATAEMISSAO) = 2024
	AND TITMMOV.CODTBORCAMENTO = '2.2.01.002'
	AND TMOV.CODCCUSTO = '01.02.01.01.02.012'
	AND TMOV.CODCOLIGADA = 1
	AND TMOV.VALORBRUTO > 0
ORDER BY IDMOV ASC