SELECT	
		TMOV.CODCOLIGADA,
		GFILIAL.CODFILIAL,
		TMOVLAN.IDMOV					AS IDMOV,
		TMOV.CODTMV,
		FLAN.IDLAN						AS REF,
		CASE											WHEN MONTH(TMOV.DATAEMISSAO) < 10 
														THEN CONCAT('0',MONTH(TMOV.DATAEMISSAO), '/', YEAR(TMOV.DATAEMISSAO))
														ELSE CONCAT(MONTH(TMOV.DATAEMISSAO), '/', YEAR(TMOV.DATAEMISSAO))
		END								AS EMISSAO,
		CASE											WHEN MONTH(FLANBAIXA.DATABAIXA) < 10 
														THEN CONCAT('0',MONTH(FLANBAIXA.DATABAIXA), '/', YEAR(FLANBAIXA.DATABAIXA))
														ELSE CONCAT(MONTH(FLANBAIXA.DATABAIXA), '/', YEAR(FLANBAIXA.DATABAIXA))
		END								AS BAIXA,
		MONTH(TMOV.DATAEMISSAO)			AS MES,
		YEAR(TMOV.DATAEMISSAO)			AS ANO,
		GCCUSTO.CODCCUSTO				AS CODCCUSTO,
		TTBORCAMENTO.CODTBORCAMENTO		AS CODNATUREZA,
		TTBORCAMENTO.DESCRICAO			AS NATUREZA,
		FLANBAIXARATCCU.VALOR			AS REALIZADO,
		0								AS COMPROMETIDO,
		FCFO.CODCFO						AS CODCFO,
		FCFO.NOME						AS FORNECEDOR
FROM	
			TMOV		(NOLOCK)
	JOIN TMOV TMOV1 (NOLOCK) 
								ON TMOV1.CODCOLIGADA = TMOV.CODCOLIGADA
								AND TMOV1.IDMOV =	(
														SELECT
															MAX(RASTREIAMOVIMENTOS.IDMOV)
														FROM
															RASTREIAMOVIMENTOS (TMOV.CODCOLIGADA, TMOV.IDMOV)
													)
	--LEFT JOIN TMOV TMOV2 (NOLOCK) 
	--							ON TMOV2.CODCOLIGADA = TMOV.CODCOLIGADA
	--							AND TMOV2.IDMOV =	(
	--													SELECT
	--														MIN(RASTREIAMOVIMENTOS.IDMOV)
	--													FROM
	--														RASTREIAMOVIMENTOS (TMOV.CODCOLIGADA, TMOV1.IDMOV)
	--												)
	JOIN GFILIAL (NOLOCK)
								ON GFILIAL.CODCOLIGADA = TMOV.CODCOLIGADA
								AND GFILIAL.CODFILIAL = TMOV.CODFILIAL
	JOIN TMOVLAN (NOLOCK)
								ON TMOV.CODCOLIGADA = TMOVLAN.CODCOLIGADA
								AND TMOV.IDMOV = TMOVLAN.IDMOV
	JOIN FLAN (NOLOCK)
								ON FLAN.CODCOLIGADA = TMOVLAN.CODCOLIGADA
								AND FLAN.IDLAN = TMOVLAN.IDLAN
	LEFT JOIN  FLANBAIXA (NOLOCK)
								ON	FLAN.CODCOLIGADA	= FLANBAIXA.CODCOLIGADA
								AND FLAN.IDLAN			= FLANBAIXA.IDLAN
	JOIN FLANBAIXARATCCU (NOLOCK) 
								ON	FLANBAIXARATCCU.CODCOLIGADA = FLANBAIXA.CODCOLIGADA
								AND FLANBAIXARATCCU.IDBAIXA		= FLANBAIXA.IDBAIXA
	JOIN TTBORCAMENTO (NOLOCK) 
								ON	TTBORCAMENTO.CODCOLIGADA	= FLANBAIXARATCCU.CODCOLNATFINANCEIRA
								AND TTBORCAMENTO.CODTBORCAMENTO = FLANBAIXARATCCU.CODNATFINANCEIRA 
	JOIN GCCUSTO (NOLOCK) 
								ON	GCCUSTO.CODCOLIGADA = FLANBAIXARATCCU.CODCOLIGADA
								AND GCCUSTO.CODCCUSTO	= FLANBAIXARATCCU.CODCCUSTO
								AND LEN(GCCUSTO.CODCCUSTO) >= 18
	JOIN GCOLIGADA (NOLOCK)
								ON GCOLIGADA.CODCOLIGADA = FLAN.CODCOLIGADA
	JOIN FCFO (NOLOCK)
								ON FCFO.CODCFO			= FLAN.CODCFO		


WHERE	
			1=1
	AND		FLANBAIXA.STATUS = 0
	AND		FLAN.PAGREC = 2
	AND		FLAN.NFOUDUP IN (0,2)
	AND		FLAN.CLASSIFICACAO <> 4
	AND		FLAN.STATUSLAN <> 2 
	AND		FLANBAIXARATCCU.VALOR > 0

	AND		MONTH(TMOV.DATAEMISSAO) = 4--IN ('01', '02', '03', '04', '05')  
	AND		YEAR(TMOV.DATAEMISSAO)	IN	(2024)
	
--	AND		TMOVLAN.IDMOV = 562537
	AND		GCCUSTO.CODCCUSTO = '01.02.01.01.02.012'
	AND		TTBORCAMENTO.CODTBORCAMENTO = '3.1.01.002'
/*
select
2449.0000+
4898.0000+
2075.0100+
2699.0000+
4157.0000+
1090.0000

*/


GROUP BY	
			GCOLIGADA.CODCOLIGADA,   
			GCOLIGADA.NOMEFANTASIA,
			FLAN.IDLAN,
			CASE
			WHEN CHARINDEX('-', GCCUSTO.NOME) >= 1 THEN LEFT(GCCUSTO.NOME, CHARINDEX('-', GCCUSTO.NOME) - 1)
			ELSE GCCUSTO.NOME
			END,
			YEAR(FLANBAIXA.DATABAIXA),
			MONTH(FLANBAIXA.DATABAIXA),
			GCCUSTO.CODCCUSTO,
			GCCUSTO.NOME,
			TTBORCAMENTO.CODTBORCAMENTO,
			TTBORCAMENTO.DESCRICAO,
			FLAN.DATAEMISSAO,
			TMOV.DATAEMISSAO,
			TMOV.DATAEMISSAO,
			FLANBAIXARATCCU.VALOR,	
			FCFO.CODCFO,
			FCFO.NOME,
			TMOVLAN.IDMOV,
			TMOV.CODTMV,
			TMOV.CODCOLIGADA,
			GFILIAL.CODFILIAL