DECLARE @IDORCAMENTO AS INT = 316825
DECLARE @IDMOV AS INT = 586918
DECLARE @IDPERIODO AS INT = 24
DECLARE @IDITMPERIODO AS INT = 5
DECLARE @CODCOLIGADA AS INT = CASE WHEN @IDPERIODO = 24 THEN 1 ELSE 2 END


/*	VERIFICA VALORES NO MOVIMENTO	*/
SELECT 
	TITMORCAMENTO.CODCOLIGADA, TITMORCAMENTO.IDORCAMENTO, TITMORCAMENTO.IDPERIODO, TITMORCAMENTO.IDITMPERIODO,	
	TITMORCAMENTO.VALORORCADO, TITMORCAMENTO.VALORREAL, TITMORCAMENTO.VALOROPCIONAL2 AS COMPROMETIDO,	
	TITMORCAMENTO.VALORRECEBIDO, TITMORCAMENTO.VALORCEDIDO, TITMORCAMENTO.VALOREXCEDENTE
FROM 
	TITMORCAMENTO (NOLOCK)
WHERE 
		1=1 
	AND TITMORCAMENTO.IDORCAMENTO = @IDORCAMENTO 
	AND TITMORCAMENTO.IDPERIODO = @IDPERIODO 
	AND TITMORCAMENTO.IDITMPERIODO = @IDITMPERIODO

/*	VERIFICA VALORES NO PRODUTO DO ORÇAMENTO	*/
SELECT DISTINCT
	TMOV.CODCOLIGADA, TMOVORCAMENTO.IDORCAMENTO, TMOV.IDMOV, TMOVORCAMENTO.IDMOVORCAMENTO, TMOVORCAMENTO.IDPERIODO, TMOVORCAMENTO.IDITMPERIODO,	
	TMOVORCAMENTO.VALORORCADO, TMOVORCAMENTO.VALORREAL, TMOVORCAMENTO.VALOROPCIONAL2 AS COMPROMETIDO,	
	TMOVORCAMENTO.VALORRECEBIDO, TMOVORCAMENTO.VALORCEDIDO, TMOVORCAMENTO.VALOREXCEDENTE , 
	CASE	WHEN TMOV.STATUS = 'A' THEN 'AVISA'
			WHEN TMOV.STATUS = 'B' THEN 'BLOQUEADO'
			WHEN TMOV.STATUS = 'F' THEN 'FATURADO'
			ELSE TMOV.STATUS END AS 'STATUS',
	TMOV.CODTMV, TMOV.CODCCUSTO, TMOV.CODCCUSTODESTINO
FROM 
				TMOV			(NOLOCK)
	LEFT JOIN	TMOVORCAMENTO	(NOLOCK) ON TMOVORCAMENTO.CODCOLIGADA = TMOV.CODCOLIGADA AND TMOVORCAMENTO.IDMOV = TMOV.IDMOV
WHERE 
		1=1
	AND TMOV.IDMOV = @IDMOV
	AND (	(TMOVORCAMENTO.IDPERIODO = @IDPERIODO AND TMOVORCAMENTO.IDORCAMENTO = @IDORCAMENTO) 
		OR	(TMOVORCAMENTO.IDPERIODO IS NOT NULL AND TMOVORCAMENTO.IDORCAMENTO IS NOT NULL)
		OR	(TMOVORCAMENTO.IDPERIODO = NULL AND TMOVORCAMENTO.IDORCAMENTO = NULL)
		)
SELECT MAX(IDMOV) AS IDMOV FROM RASTREIAMOVIMENTOS (@CODCOLIGADA, @IDMOV)