SELECT
	TITMTMV.CODCOLIGADA,
	CASE TTMV.CLASSIFICACAO		WHEN '04.04.04' THEN 'Estoque > Requisição de Material'		WHEN '04.04.05' THEN 'Estoque > Baixa de Estoque'		WHEN '04.04.06' THEN 'Estoque > Transferências'		WHEN '04.04.08' THEN 'Estoque > Produção > Movimentação'		WHEN '04.04.10' THEN 'Estoque > Estoque de Terceiros'		WHEN '04.06.01' THEN 'Compras > Solicitação de Compra'		WHEN '04.06.02' THEN 'Compras > Cotação'		WHEN '04.06.04' THEN 'Compras > Ordem de Compras'		WHEN '04.06.05' THEN 'Compras > Recebimento de Materiais'		WHEN '04.06.06' THEN 'Compras > Importação'		WHEN '04.06.07' THEN 'Compras > Aquisição de Serviços'		WHEN '04.06.08' THEN 'Compras > Devolução de Compras'		WHEN '04.07'    THEN 'Outras Movimentações > Controle de Imobilizado'		WHEN '04.08.01' THEN 'Vendas > Pedido de Vendas'		WHEN '04.08.02' THEN 'Vendas > Faturamento > Movimentação'		WHEN '04.08.03' THEN 'Vendas > Exportações'		WHEN '04.08.04' THEN 'Vendas > Devolução de Vendas'		WHEN '04.09'    THEN 'Outras Movimentações > Outras Movimentações'		ELSE TTMV.CLASSIFICACAO + ' - A localizar'
	END																																							AS 'MENU_LOCAL', 
	TITMTMV.CODTMV																																				AS 'CODTMV', 
	    CASE 
        WHEN TITMTMV.EFEITOSALDOORCA = 'T' THEN 'AUMENTA O COMPROMETIDO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'N' THEN 'NENHUM EFEITO NO ORÇAMENTO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'M' THEN 'AUMENTA O EMPENHADO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'D' THEN 'DIMINUI O REALIZADO' 
        WHEN TITMTMV.EFEITOSALDOORCA = 'A' THEN 'AUMENTA O REALIZADO' 
    END																																							AS 'EFEITO NO SALDO DO ORÇAMENTO',
	TTMV.NOME																																					AS 'NOME',
	CASE WHEN TITMTMV.HABILITAORCAMENTO = 1 THEN 'ATIVO' ELSE 'INATIVO' END AS 'HABILITA ORÇAMENTO',
    CASE WHEN TTMVEXT.BUSCARNATORCDEFAULTPRD = 'D' THEN 'DESPESA' 
		 WHEN TTMVEXT.BUSCARNATORCDEFAULTPRD = 'R' THEN 'RECEITA' 
		 ELSE TTMVEXT.BUSCARNATORCDEFAULTPRD							
	END																																							AS 'BUSCAR DEFAULT DO PRODUTO',
	 CASE 
        WHEN TITMTMV.LIMESTOUROORCAMENTO = 'A' THEN 'AVISA' 
        WHEN TITMTMV.LIMESTOUROORCAMENTO = 'L' THEN 'BLOQUEIA' 
    END																																							AS 'LIMITE DE ESTOURO DO ORÇAMENTO',
	CASE TTMV.CONTABILLAN
		WHEN 'N' THEN 'Nâo Contábil'
		WHEN 'B' THEN 'Baixa Contábil'
		WHEN 'C' THEN 'Contábil'
		WHEN 'A' THEN 'A Contabilizar'
		ELSE 'Sem parametrização'
	END																																							AS 'CONT_FINANCEIRO',
	CONVERT(VARCHAR(15), (SELECT MAX(TMOV.DATAEMISSAO) FROM TMOV WITH (NOLOCK) WHERE TMOV.CODCOLIGADA = TTMV.CODCOLIGADA AND TMOV.CODTMV = TTMV.CODTMV), 103)	AS 'ULTIMO_MOVIMENTO'

FROM 
				TITMTMV			WITH (NOLOCK)
	JOIN		TTMV			WITH (NOLOCK) ON TTMV.CODCOLIGADA = TITMTMV.CODCOLIGADA AND TTMV.CODTMV = TITMTMV.CODTMV
	JOIN		TTMVEXT			WITH (NOLOCK) ON TTMVEXT.CODCOLIGADA = TTMV.CODCOLIGADA AND TTMVEXT.CODTMV = TTMV.CODTMV
	LEFT JOIN	TMOTIVOREFMOV	WITH (NOLOCK) ON TMOTIVOREFMOV.CODCOLIGADA = TTMVEXT.CODCOLIGADA AND TMOTIVOREFMOV.IDMOTIVOREF = TTMVEXT.IDMOTIVOREF

WHERE 
		1=1
	AND TITMTMV.CODCOLIGADA IN (1, 2)
--	AND TITMTMV.CODTMV LIKE '1.2.%'
--	AND TITMTMV.EFEITOSALDOORCA <> 'A'

ORDER BY 
	TITMTMV.CODCOLIGADA,
	TITMTMV.CODTMV
