SELECT A.CODTMV, A.NOME, B.CODTMVFAT, C.NOME
FROM TTMV A WITH (NOLOCK)
   JOIN TTMVFATURAMENTO B WITH (NOLOCK) ON B.CODCOLIGADA = A.CODCOLIGADA AND B.CODTMV = A.CODTMV
   JOIN TTMV C WITH (NOLOCK) ON C.CODCOLIGADA = B.CODCOLIGADA AND C.CODTMV = B.CODTMVFAT
WHERE A.CODCOLIGADA = 1

UNION
SELECT A.CODTMV, A.NOME, A.CODTMVPED, B.NOME
FROM TTMV A WITH (NOLOCK)
   JOIN TTMV B WITH (NOLOCK) ON B.CODCOLIGADA = A.CODCOLIGADA AND B.CODTMV = A.CODTMVPED
WHERE A.CODCOLIGADA = 1
ORDER BY A.CODTMV